import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import readline from 'node:readline';
import {spawn} from 'node:child_process';
const project=path.resolve(import.meta.dirname,'..');
function launch(root){const child=spawn(process.execPath,[path.join(project,'native','bridge.mjs'),root],{stdio:['pipe','pipe','pipe'],windowsHide:true});let seq=0;const pending=new Map();readline.createInterface({input:child.stdout}).on('line',line=>{const r=JSON.parse(line);const p=pending.get(r.id);pending.delete(r.id);r.error?p.reject(new Error(r.error)):p.resolve(r.value);});child.on('exit',()=>{for(const p of pending.values())p.reject(new Error('bridge exited'));});return {child,call(command,body){return new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});child.stdin.write(JSON.stringify({id,command,body})+'\n');});}};}
test('native transport plays, guards replay, restores turns and persists career stats without HTTP',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'afterhours-native-'));t.after(()=>{assert.ok(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep)&&path.basename(root).startsWith('afterhours-native-'));fs.rmSync(root,{recursive:true,force:true});});let client=launch(root);const initial=await client.call('state',null);assert.equal(initial.profile.wallet,20000);let s=await client.call('start',{config:{seats:2,stakeLevel:'low',buyBB:100,durationMinutes:15}});const turn=()=>({sessionId:s.session.id,handNumber:s.session.hand.number,eventCount:s.session.hand.eventCount});const original=JSON.stringify(s.session.hand);await assert.rejects(client.call('action',{...turn(),eventCount:-1,action:'fold'}),/已更新/);await assert.rejects(client.call('history?session=current&hand=1'),/大厅/);await client.call('pause',{paused:true});await assert.rejects(client.call('tick',turn()),/暂停/);await new Promise(r=>setTimeout(r,35));await client.call('pause',{paused:false});let exited=new Promise(r=>client.child.once('exit',r));await client.call('shutdown');await exited;client=launch(root);s=await client.call('state');assert.equal(s.session.hand.number,1);assert.equal(s.session.hand.eventCount,JSON.parse(original).eventCount);let guard=0;while(s.session.hand.status==='playing'){assert.ok(++guard<180);s=await client.call(s.session.hand.legal?'action':'tick',{...turn(),...(s.session.hand.legal?{action:s.session.hand.legal.canCheck?'check':'call'}:{})});}const compact=await client.call('compact-history?hand=1');assert.ok(compact.hand.events.length>=5);assert.equal(compact.hand.deck,undefined);const completed=s.session.completedHands;const opponent=s.session.players[1];await client.call('mark',{characterId:opponent.characterId,mark:'TAG'});s=await client.call('end',{sessionId:s.session.id,reason:'test'});assert.equal(s.lastSummary.completedHands,completed,'leaving must not play fictional future hands');const archives=await client.call('archives');assert.equal(archives.sessions.length,1);const replay=await client.call('history?session='+s.lastSummary.id+'&hand=1');assert.ok(replay.hand.events.length>=5);assert.ok(replay.hand.events.every(e=>e.snapshot&&Array.isArray(e.snapshot.players)));const contacts=await client.call('contacts');assert.ok(contacts.players.find(x=>x.characterId===opponent.characterId).stats.hands>=1);assert.equal(s.profile.marks[opponent.characterId],'TAG');exited=new Promise(r=>client.child.once('exit',r));await client.call('shutdown');await exited;});
