using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media;
using System.Windows.Markup;

namespace AfterHours {
public partial class MainWindow {
 string[] stakeIds={"low","mid","high","master","top"},stakeNames={"低级场","中级场","高级场","大师场","顶级场"};int[] bigBlinds={2,10,50,200,1000};int selectedStake=0;ComboBox seatsCombo,buyCombo,timeCombo;
 const double LobbyWidth=1672,LobbyHeight=941;

 Border LobbyPanel(UIElement child,double width,double height,double radius=10){return new Border{Width=width,Height=height,Child=child,Background=new SolidColorBrush(Color.FromArgb(231,8,22,20)),BorderBrush=UI.Brush("#3E6157"),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(radius),SnapsToDevicePixels=true};}
 Button LobbyButton(string label,Action action,double width,bool active=false){var button=UI.Button(label,action,width,active);button.Margin=new Thickness(0);button.Height=53;button.MinHeight=0;button.FontSize=16;button.HorizontalContentAlignment=HorizontalAlignment.Left;button.Padding=new Thickness(20,0,12,0);button.Background=active?new LinearGradientBrush(UI.Brush("#159B68").Color,UI.Brush("#064C37").Color,90):new LinearGradientBrush(UI.Brush("#14221F").Color,UI.Brush("#091311").Color,90);button.BorderBrush=UI.Brush(active?"#54E2AA":"#2B4740");return button;}
 Button LobbyStake(int index){bool active=index==selectedStake;var button=UI.Button("",()=>{selectedStake=index;Render();},263,active);button.Margin=new Thickness(0);button.Height=95;button.MinHeight=0;button.Padding=new Thickness(0);button.Background=active?new LinearGradientBrush(UI.Brush("#0E8E62").Color,UI.Brush("#07392D").Color,90):new LinearGradientBrush(UI.Brush("#1A2830").Color,UI.Brush("#0B1215").Color,90);button.BorderBrush=UI.Brush(active?"#46E6A5":"#354E51");var text=UI.Stack();text.HorizontalAlignment=HorizontalAlignment.Center;text.VerticalAlignment=VerticalAlignment.Center;var name=UI.Text(stakeNames[index],17,UI.Ink,true);name.TextAlignment=TextAlignment.Center;text.Children.Add(name);var blinds=UI.Text(UI.Money(bigBlinds[index]/2)+" / "+UI.Money(bigBlinds[index]),17,UI.Ink,true);blinds.TextAlignment=TextAlignment.Center;text.Children.Add(blinds);button.Content=text;return button;}
 StackPanel LobbyField(string title,FrameworkElement input,double width){var field=UI.Stack();field.Width=width;var label=UI.Text(title,13,UI.Muted);label.Margin=new Thickness(0,0,0,6);field.Children.Add(label);input.Width=width;input.Margin=new Thickness(0);input.MinHeight=46;field.Children.Add(input);return field;}
 void At(Canvas canvas,UIElement child,double x,double y){UI.At(canvas,child,x,y);}

 void RenderLobby(){
  var canvas=new Canvas{Width=LobbyWidth,Height=LobbyHeight,Background=UI.Brush("#020806"),ClipToBounds=true};var reference=Image(Path.Combine(root,"素材","主页界面","1.png"));if(reference!=null){canvas.Children.Add(new System.Windows.Controls.Image{Source=reference,Width=LobbyWidth,Height=LobbyHeight,Stretch=Stretch.Fill,Opacity=.34});}canvas.Children.Add(new Border{Width=LobbyWidth,Height=LobbyHeight,Background=new SolidColorBrush(Color.FromArgb(128,0,7,5))});
  var brand=UI.Stack();brand.Children.Add(UI.Text("AFTERHOURS",31,UI.Ink,true));brand.Children.Add(UI.Text("PRIVATE POKER CLUB  /  私人扑克俱乐部",12,UI.Muted));At(canvas,brand,27,18);
  var account=new Grid{Width=390,Height=62};account.ColumnDefinitions.Add(new ColumnDefinition());account.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(122)});account.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(136)});var greeting=UI.Text((DateTime.Now.Hour<6?"夜深了":DateTime.Now.Hour<12?"早上好":DateTime.Now.Hour<18?"下午好":"晚上好")+"，欢迎入座",14,UI.Muted);greeting.HorizontalAlignment=HorizontalAlignment.Right;greeting.VerticalAlignment=VerticalAlignment.Center;account.Children.Add(greeting);var money=UI.Text(UI.Money(state["profile"]["wallet"].N),26,UI.Ink,true);money.HorizontalAlignment=HorizontalAlignment.Center;money.VerticalAlignment=VerticalAlignment.Center;Grid.SetColumn(money,1);account.Children.Add(money);var daily=UI.Button("上线补助",async()=>await Run("claim-daily",J.O()),132,true);daily.Height=54;daily.Margin=new Thickness(2,4,2,4);daily.FontSize=16;Grid.SetColumn(daily,2);account.Children.Add(daily);var accountPanel=LobbyPanel(account,390,62,9);At(canvas,accountPanel,1170,18);var gear=LobbyButton("⚙",async()=>await ShowSettings(),51);gear.Height=51;gear.FontSize=21;gear.Padding=new Thickness(0);gear.HorizontalContentAlignment=HorizontalAlignment.Center;At(canvas,gear,1595,23);
  var navTitle=UI.Text("俱乐部",13,UI.Muted);At(canvas,navTitle,27,94);string[] navLabels={"♠   现金桌大厅","▷   牌局复盘","♟   牌友档案","⚙   游戏设置","♫   音乐与音效","?   游戏指南"};Action[] navActions={new Action(Render),async()=>await ShowReplay(),async()=>await ShowContacts(),async()=>await ShowSettings(),new Action(ShowMusic),new Action(ShowGuide)};for(int i=0;i<navLabels.Length;i++){var nav=LobbyButton(navLabels[i],navActions[i],188,i==0);At(canvas,nav,24,111+i*61);}var system=UI.Text("系统",13,UI.Muted);At(canvas,system,27,487);var exit=LobbyButton("⏻   退出游戏",RequestExit,188);exit.Background=new LinearGradientBrush(UI.Brush("#9A3D45").Color,UI.Brush("#572025").Color,90);exit.BorderBrush=UI.Brush("#D9797C");At(canvas,exit,24,515);
  var world=state["world"];var online=UI.Stack();online.Children.Add(UI.Text("●  "+world["onlineCount"].S+" 位牌友在线",16,UI.Brush("#5BE5A8")));online.Children.Add(UI.Text("共 "+world["totalCount"].S+" 位牌友\n本地在线 "+world["localOnlineCount"].S+"\nAI 在线 "+world["aiOnlineCount"].S,14,UI.Muted));At(canvas,online,28,584);var motto=LobbyPanel(UI.Stack(),183,170,9);var mottoText=UI.Stack();mottoText.HorizontalAlignment=HorizontalAlignment.Center;mottoText.VerticalAlignment=VerticalAlignment.Center;var icon=UI.Text("♠",53,UI.Gold);icon.TextAlignment=TextAlignment.Center;mottoText.Children.Add(icon);var line1=UI.Text("GOOD PLAYERS",14,UI.Gold,true);line1.TextAlignment=TextAlignment.Center;mottoText.Children.Add(line1);var line2=UI.Text("BETTER NIGHTS",14,UI.Gold,true);line2.TextAlignment=TextAlignment.Center;mottoText.Children.Add(line2);motto.Child=mottoText;At(canvas,motto,25,712);
  var hero=new Grid{Width=1412,Height=274,ClipToBounds=true};var heroSource=new Canvas{Width=1412,Height=274,ClipToBounds=true};if(reference!=null){var crop=new System.Windows.Controls.Image{Source=reference,Width=LobbyWidth,Height=LobbyHeight,Stretch=Stretch.Fill};At(heroSource,crop,-235,-94);}hero.Children.Add(heroSource);var heroOverlay=new Canvas{Width=1412,Height=274};if(state["ai"]["mode"].S=="external"){var modePatch=new Canvas{Width=300,Height=28};At(modePatch,new Border{Width=300,Height=28,Background=new SolidColorBrush(Color.FromArgb(220,1,10,8))},0,0);At(modePatch,UI.Text("当前模式：外部 AI",16,UI.Brush("#5DE0A4"),true),0,2);At(heroOverlay,modePatch,236,164);}hero.Children.Add(heroOverlay);var heroFrame=LobbyPanel(hero,1412,274,11);At(canvas,heroFrame,235,94);
  var stakeContent=new Canvas{Width=1412,Height=153};var stakeHeading=UI.Text("♠  选择现金桌",22,UI.Ink,true);At(stakeContent,stakeHeading,22,16);var subHeading=UI.Text("不同级别，匹配你的节奏。",15,UI.Muted);At(stakeContent,subHeading,197,21);var tagline=UI.Text("♠  SAME GAME  ·  HIGHER STORIES",12,UI.Gold,true);At(stakeContent,tagline,1110,24);for(int i=0;i<5;i++)At(stakeContent,LobbyStake(i),17+i*278,59);var stakePanel=LobbyPanel(stakeContent,1412,153,10);At(canvas,stakePanel,235,382);
  var setupContent=new Canvas{Width=1377,Height=158};var setupHeading=UI.Text("自定义开桌设置",20,UI.Ink,true);At(setupContent,setupHeading,18,14);var setupSub=UI.Text("快速设置并开始你的牌局",14,UI.Muted);At(setupContent,setupSub,165,19);var dividerLine=new Border{Width=1339,Height=1,Background=UI.Brush("#29433D")};At(setupContent,dividerLine,18,51);seatsCombo=UI.Combo(new[]{"2 人","3 人","5 人","7 人"},3,164);buyCombo=UI.Combo(new[]{"50 BB","100 BB","200 BB","300 BB","500 BB"},1,190);timeCombo=UI.Combo(new[]{"15 分钟","30 分钟","60 分钟","120 分钟"},2,180);At(setupContent,LobbyField("牌桌人数",seatsCombo,164),18,69);At(setupContent,LobbyField("带入筹码",buyCombo,190),205,69);At(setupContent,LobbyField("开桌时长",timeCombo,180),420,69);var allow=UI.Check("允许 Straddle",true);allow.Margin=new Thickness(0);allow.FontSize=16;At(setupContent,allow,630,105);var deposit=UI.Text("带入 "+UI.Money(bigBlinds[selectedStake]*100),20,UI.Gold,true);buyCombo.SelectionChanged+=(s,e)=>deposit.Text="带入 "+UI.Money(bigBlinds[selectedStake]*new[]{50,100,200,300,500}[Math.Max(0,buyCombo.SelectedIndex)]);var start=UI.Button("♠   入座开局  →",async()=>{await Run("start",J.O("config",J.O("stakeLevel",stakeIds[selectedStake],"seats",new[]{2,3,5,7}[seatsCombo.SelectedIndex],"buyBB",new[]{50,100,200,300,500}[buyCombo.SelectedIndex],"durationMinutes",new[]{15,30,60,120}[timeCombo.SelectedIndex],"straddleEnabled",allow.IsChecked==true)));},279,true);start.Height=72;start.Margin=new Thickness(0);start.FontSize=21;At(setupContent,start,821,70);var depositPanel=LobbyPanel(deposit,240,72,8);deposit.TextAlignment=TextAlignment.Center;deposit.VerticalAlignment=VerticalAlignment.Center;depositPanel.Child=deposit;At(setupContent,depositPanel,1120,70);var setupPanel=LobbyPanel(setupContent,1377,158,10);At(canvas,setupPanel,254,553);
  var careerContent=new Grid{Width=490,Height=120};careerContent.ColumnDefinitions.Add(new ColumnDefinition());careerContent.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(195)});var careerText=UI.Stack();careerText.Margin=new Thickness(28,22,0,0);careerText.Children.Add(UI.Text("▮▮  生涯战绩",19,UI.Ink,true));careerText.Children.Add(UI.Text("生涯 "+state["profile"]["lifetimeHands"].S+" 手   ·   净盈亏 "+UI.Money(state["profile"]["lifetimeProfit"].N),15,UI.Muted));careerContent.Children.Add(careerText);var summary=UI.Button("查看上一场结算",ShowSummary,170);summary.Height=50;summary.Margin=new Thickness(10,33,15,0);Grid.SetColumn(summary,1);careerContent.Children.Add(summary);var careerPanel=LobbyPanel(careerContent,490,120,10);At(canvas,careerPanel,235,738);
  var continueContent=new Canvas{Width=910,Height=120};var trophy=UI.Text("♛",44,UI.Gold);At(continueContent,trophy,30,30);var continueTitle=UI.Text("继续你的扑克之夜",21,UI.Gold,true);At(continueContent,continueTitle,100,33);var continueBody=UI.Text("好牌，永远在下一桌。",15,UI.Muted);At(continueContent,continueBody,100,64);var continueHint=UI.Text("▶",22,UI.Gold);At(continueContent,continueHint,300,48);var continuePanel=LobbyPanel(continueContent,910,120,10);At(canvas,continuePanel,738,738);
  var footer=UI.Text("MORE THAN A GAME   ◆   A PRIVATE CIRCLE   ◆   AFTERHOURS",12,UI.Gold);footer.TextAlignment=TextAlignment.Center;footer.Width=650;At(canvas,footer,518,891);var version=UI.Text("v1.0.2",12,UI.Muted);At(canvas,version,29,898);body.Children.Add(new Viewbox{Stretch=Stretch.Fill,Child=canvas});
 }
 UIElement Field(string name,UIElement input){var s=UI.Stack();s.Children.Add(UI.Text(name,13,UI.Muted));s.Children.Add(input);return s;}
 void ShowSummary(){var summary=state["lastSummary"];if(summary.Null){Notice("还没有结束的场次。");return;}StackPanel p,f;var d=Dialog("本场已结束",out p,out f);p.Children.Add(UI.Text(summary["reason"].S,15,UI.Muted));p.Children.Add(UI.Text((summary["profit"].N>=0?"+":"")+UI.Money(summary["profit"].N),44,summary["profit"].N>=0?UI.Brush("#70DBAC"):UI.Brush("#FF7C8B"),true));p.Children.Add(UI.Text("完成 "+summary["completedHands"].S+" 手\n带入 "+UI.Money(summary["buyIns"].N)+"\n回存 "+UI.Money(summary["cashout"].N)+"\n账户 "+UI.Money(summary["wallet"].N),20));p.Children.Add(UI.Text("本场报告已写入「日志」文件夹。下桌后可判断本场对手的牌风。",15,UI.Muted));f.Children.Add(UI.Button("牌友档案 / 身份竞猜",async()=>await ShowContacts()));f.Children.Add(UI.Button("详细复盘",async()=>await ShowReplay(),150,true));ShowOverlay(d,900,570);}
 Slider BankSlider(double minimum,double maximum,double value,double step){var slider=new Slider{Minimum=minimum,Maximum=Math.Max(minimum,maximum),Value=Math.Max(minimum,Math.Min(maximum,value)),TickFrequency=Math.Max(1,step),IsSnapToTickEnabled=true,IsMoveToPointEnabled=true,Width=650,Height=42,Margin=new Thickness(0,4,0,2)};slider.Template=(ControlTemplate)XamlReader.Parse("<ControlTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='Slider'><Grid Margin='4,0'><Border Height='8' Background='#10251F' BorderBrush='#355C50' BorderThickness='1' CornerRadius='4' VerticalAlignment='Center'/><Track x:Name='PART_Track' Minimum='{TemplateBinding Minimum}' Maximum='{TemplateBinding Maximum}' Value='{TemplateBinding Value}' Orientation='Horizontal'><Track.DecreaseRepeatButton><RepeatButton Command='Slider.DecreaseLarge'><RepeatButton.Template><ControlTemplate TargetType='RepeatButton'><Border Height='8' Background='#0C9866' CornerRadius='4' VerticalAlignment='Center'/></ControlTemplate></RepeatButton.Template></RepeatButton></Track.DecreaseRepeatButton><Track.Thumb><Thumb Width='22' Height='22'><Thumb.Template><ControlTemplate TargetType='Thumb'><Grid><Ellipse Fill='#E3C46E' Stroke='#FFF0B5' StrokeThickness='1.2'/><Ellipse Width='8' Height='8' Fill='#0B513B'/></Grid></ControlTemplate></Thumb.Template></Thumb></Track.Thumb><Track.IncreaseRepeatButton><RepeatButton Command='Slider.IncreaseLarge' Opacity='0'/></Track.IncreaseRepeatButton></Track></Grid></ControlTemplate>");return slider;}
 Border BankSection(UIElement content){var panel=UI.Box(content,UI.Brush("#0C211B"),10,new Thickness(16,12,16,14));panel.BorderBrush=UI.Brush("#315D50");panel.BorderThickness=new Thickness(1);panel.Margin=new Thickness(0,0,0,12);return panel;}
 void ShowBank(){StackPanel p,f;var d=Dialog("筹码管理",out p,out f);int bb=Math.Max(1,Session["config"]["bb"].I),stack=(int)Math.Floor(Hero["stack"].N),wallet=(int)Math.Floor(state["profile"]["wallet"].N);p.Children.Add(UI.Text("账户 "+UI.Money(wallet)+"  ·  桌上 "+UI.Money(stack),22,UI.Ink,true));var note=UI.Text("拖动滑杆选择金额。补码目标为 50–500 BB；本手已投入底池的筹码不可退回。",14,UI.Muted);note.Margin=new Thickness(0,3,0,16);p.Children.Add(note);
  int rebuyMin=Math.Max(bb*50,stack+bb),rebuyMax=Math.Min(bb*500,stack+wallet);bool canRebuy=rebuyMax>=rebuyMin;var rebuy=BankSlider(rebuyMin,canRebuy?rebuyMax:rebuyMin,Math.Max(rebuyMin,Math.Min(rebuyMax,bb*100)),bb);rebuy.IsEnabled=canRebuy;var rebuyValue=UI.Text("",23,UI.Gold,true);var rebuyDetail=UI.Text("",13,UI.Muted);Action updateRebuy=()=>{int target=(int)Math.Round(rebuy.Value);rebuyValue.Text="补至 "+UI.Money(target);rebuyDetail.Text="本次补码 "+UI.Money(Math.Max(0,target-stack))+"  ·  "+(target/(double)bb).ToString("0")+" BB";};rebuy.ValueChanged+=(s,e)=>updateRebuy();updateRebuy();var rebuyContent=UI.Stack();rebuyContent.Children.Add(UI.Text("补码目标",15,UI.Ink,true));rebuyContent.Children.Add(rebuyValue);rebuyContent.Children.Add(rebuyDetail);rebuyContent.Children.Add(rebuy);if(!canRebuy){var unavailable=UI.Text(wallet<bb?"账户余额不足以完成至少 1 BB 的补码。":"当前筹码已达到该级别补码上限。",13,UI.Brush("#D9A66D"));unavailable.Margin=new Thickness(0,5,0,0);rebuyContent.Children.Add(unavailable);}p.Children.Add(BankSection(rebuyContent));
  int cashMax=Math.Max(0,stack);var cash=BankSlider(0,Math.Max(1,cashMax),0,bb);cash.IsEnabled=cashMax>0;var cashValue=UI.Text("退回 "+UI.Money(0),23,UI.Brush("#D9E9E0"),true);var cashDetail=UI.Text("可退回上限 "+UI.Money(cashMax)+"  ·  不包含本手已投入底池的筹码",13,UI.Muted);cash.ValueChanged+=(s,e)=>cashValue.Text="退回 "+UI.Money(Math.Round(cash.Value));var cashContent=UI.Stack();cashContent.Children.Add(UI.Text("退码金额",15,UI.Ink,true));cashContent.Children.Add(cashValue);cashContent.Children.Add(cashDetail);cashContent.Children.Add(cash);p.Children.Add(BankSection(cashContent));
  var grant=UI.Button("领取可用补助",async()=>{if(await Run("claim-daily",J.O())){HideOverlay();ShowBank();}},180);grant.HorizontalAlignment=HorizontalAlignment.Left;grant.Margin=new Thickness(0,0,0,4);p.Children.Add(grant);f.Children.Add(UI.Button("退码",async()=>{int amount=(int)Math.Round(cash.Value);if(amount<=0){ShowGameMessage("退码金额","请先拖动滑杆选择要退回账户的筹码。");return;}if(await Run("cashout",Turn("amount",amount)))HideOverlay();},135));f.Children.Add(UI.Button("补码",async()=>{if(!canRebuy){ShowGameMessage("暂时无法补码","请先确认账户余额或当前筹码上限。");return;}int target=(int)Math.Round(rebuy.Value);if(await Run("rebuy",Turn("target",target)))HideOverlay();},145,true));ShowOverlay(d,820,640);}
}
}
