using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Media.Animation;
using System.Windows.Threading;
using System.Security.Cryptography;
using System.Text;

namespace AfterHours {
public partial class MainWindow : Window {
 readonly string root,dataRoot;readonly bool qa;RulesClient rules;J state=new J(null),preferences=new J(null),avatarMap=new J(null);Grid shell=new Grid(),body=new Grid(),overlay=new Grid();TextBlock status,clockText,actionClock;DispatcherTimer timer,clockAnimator;bool busy,paused,fastFold,straddleNext,closing,reviewHold,endingTable;DateTime settleAt=DateTime.MaxValue,lastPoll=DateTime.MinValue,bufferUntil=DateTime.MinValue,pauseAt;string seenHand="",lastSound="";int dialogCount,stateRevision;double raiseTo;bool sounds=true;string heroAvatar="";double fontScale=1;Dictionary<string,ImageSource> bitmapCache=new Dictionary<string,ImageSource>();Dictionary<string,string> pokerFaceAssets=new Dictionary<string,string>();
 J Session{get{return state["session"];}} J Hand{get{return Session["hand"];}} J Hero{get{return Session["players"][0];}}
 public MainWindow(string folder,bool test){root=folder;qa=test;dataRoot=qa?Path.Combine(root,"qa","data"):root;Directory.CreateDirectory(dataRoot);Title="AFTERHOURS · 私人扑克俱乐部";Width=1664;Height=935;MinWidth=1060;MinHeight=700;WindowStartupLocation=WindowStartupLocation.CenterScreen;Background=UI.Brush("#030908");Foreground=UI.Ink;FontFamily=new FontFamily("Microsoft YaHei UI");if(!qa)WindowState=WindowState.Maximized;
  if(File.Exists(Path.Combine(dataRoot,"native-settings.json")))try{preferences=J.Parse(File.ReadAllText(Path.Combine(dataRoot,"native-settings.json")));heroAvatar=preferences["avatar"].S;sounds=preferences["sounds"].Null||preferences["sounds"].B;fontScale=preferences["fontScale"].Null?1:preferences["fontScale"].N;}catch{}
  UI.Scale=fontScale;avatarMap=J.Parse(File.ReadAllText(Path.Combine(root,"assets","avatar-map.json")));LoadPokerFaceAssets();shell.RowDefinitions.Add(new RowDefinition());shell.RowDefinitions.Add(new RowDefinition{Height=new GridLength(28)});shell.Children.Add(body);shell.Children.Add(overlay);status=UI.Text("正在载入私人俱乐部…",12,UI.Muted);status.Margin=new Thickness(18,0,0,0);Grid.SetRow(status,1);shell.Children.Add(status);shell.Background=Background;Content=shell;
  KeyDown+=(s,e)=>{if(e.Key==Key.F&&!(e.OriginalSource is TextBox)&&!(e.OriginalSource is System.Windows.Controls.Primitives.TextBoxBase))ToggleFastFold();if(e.Key==Key.Escape){if(dialogCount>0){if(compactReviewPaused)CloseCompactReview();else HideOverlay();}else if(WindowStyle==WindowStyle.None)SetFullscreen(false);}if(e.Key==Key.F11)SetFullscreen(WindowStyle!=WindowStyle.None);};
  Closing+=async(s,e)=>{if(closing)return;e.Cancel=true;if(busy){Notice("正在保存当前行动，请稍候再关闭。");return;}busy=true;try{if(!Session.Null)await rules.Call("pause",J.O("paused",false));await rules.Call("shutdown");}catch{}finally{closing=true;StopAudio();if(timer!=null)timer.Stop();if(clockAnimator!=null)clockAnimator.Stop();if(rules!=null)rules.Dispose();Close();}};
  Loaded+=async(s,e)=>{try{rules=new RulesClient(root,qa?dataRoot:null);await RestoreKey();state=await rules.Call("state");if(!Session.Null){await rules.Call("pause",J.O("paused",false));}Render();timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(250)};timer.Tick+=async(a,b)=>await Pulse();if(!qa){timer.Start();clockAnimator=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(50)};clockAnimator.Tick+=(a,b)=>UpdateAvatarClock();clockAnimator.Start();}StartMusic();if(qa)await RunQA();}catch(Exception ex){File.WriteAllText(Path.Combine(dataRoot,"initialization-error.txt"),ex.ToString());Notice(ex.Message);}};
 }
 async Task RestoreKey(){string f=Path.Combine(dataRoot,".poker-data","ai-settings.json");if(!File.Exists(f))return;try{string cipher=J.Parse(File.ReadAllText(f))["encryptedKey"].S;if(cipher.StartsWith("dpapi:")){string key=Encoding.UTF8.GetString(ProtectedData.Unprotect(Convert.FromBase64String(cipher.Substring(6)),null,DataProtectionScope.CurrentUser));await rules.Call("key-init",J.O("key",key));}}catch{Notice("当前 Windows 账户无法解密已保存的 Key，请在设置中重新填写。");}}
 void SavePreferences(){File.WriteAllText(Path.Combine(dataRoot,"native-settings.json"),J.Json(J.O("avatar",heroAvatar,"sounds",sounds,"fontScale",fontScale,"musicVolume",musicPlayer.Volume,"musicEnabled",musicEnabled)),Encoding.UTF8);}
 void Notice(string text){status.Text=text;if(!Session.Null&&text!="进度已自动保存"){ShowTableNotice(text);}}
 Dictionary<string,object> Turn(params object[] pairs){var d=J.O("sessionId",Session["id"].S,"handNumber",Hand["number"].I,"eventCount",Hand["eventCount"].I);foreach(var p in J.O(pairs))d[p.Key]=p.Value;return d;}
 async Task<bool> Run(string command,object data=null,bool repaint=true,bool interrupt=false){if(endingTable&&command!="end")return false;if(busy&&!interrupt)return false;int revision=++stateRevision;if(!interrupt)busy=true;try{J next=await rules.Call(command,data);if(revision!=stateRevision)return true;if(!next["app"].Null){bool wasSeated=!Session.Null;state=next;if(Session.Null){fastFold=false;straddleNext=false;paused=false;}if(repaint)Render();if(wasSeated&&Session.Null){HideOverlay();if(!repaint)Render();ShowSummary();}}Notice(!next["message"].Null?next["message"].S:"进度已自动保存");return true;}catch(Exception ex){if(revision==stateRevision){Notice(ex.Message);if(command!="tick")ShowGameMessage("操作未完成",ex.Message);}return false;}finally{if(!interrupt)busy=false;}}
 async Task Act(string action,double amount=0){if(endingTable||paused||Hand["legal"].Null)return;if(busy){Notice("正在提交操作…");return;}fastFold=false;HideOverlay();bufferUntil=DateTime.MinValue;bool accepted=await Run("action",Turn("action",action,"amount",(int)amount));if(accepted)bufferUntil=DateTime.UtcNow.AddMilliseconds(350);}
 async Task Pulse(){if(closing||endingTable||state.Null)return;UpdateClocks();if(busy||paused||dialogCount>0)return;if(Session.Null){if((DateTime.UtcNow-lastPoll).TotalMinutes>=1){lastPoll=DateTime.UtcNow;await Run("state",null,false);}return;}
  if(Hand["status"].S=="complete"){if(settleAt==DateTime.MaxValue)settleAt=DateTime.UtcNow.AddSeconds(5);if(!reviewHold&&DateTime.UtcNow>=settleAt){await NextHand();}return;}
  if(DateTime.UtcNow<bufferUntil)return;
  if(!Hand["actor"].Null&&Hand["actor"].I==0){if(fastFold&&Hand["street"].S=="preflop"){await Act("fold");return;}double deadline=Hand["actionDeadlineAt"].N;if(deadline>0&&DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()>=deadline)await Run("timeout",Turn());return;}
  if((DateTime.UtcNow-lastPoll).TotalMilliseconds<500)return;lastPoll=DateTime.UtcNow;int count=Hand["eventCount"].I;string oldHand=Hand["number"].S;await Run("tick",Turn("botTiming",true),false);if(count!=Hand["eventCount"].I||oldHand!=Hand["number"].S||Session.Null){bool heroTurn=!Session.Null&&!Hand["actor"].Null&&Hand["actor"].I==0;bufferUntil=DateTime.UtcNow.AddMilliseconds(Hero["folded"].B||heroTurn?0:350);Render();}
 }
 async Task NextHand(){if(endingTable||busy)return;if(Hero["stack"].N<Session["config"]["bb"].N){reviewHold=true;Notice("筹码不足，请补码或结束本场。");return;}HideOverlay();reviewHold=false;settleAt=DateTime.MaxValue;bool straddle=straddleNext;straddleNext=false;int previous=Hand["number"].I;await Run("next",Turn("playerStraddle",straddle));if(!Session.Null&&Hand["number"].I==previous)reviewHold=true;}
 void UpdateClocks(){UpdateAvatarClock();if(clockText!=null&&!Session.Null){DateTime end;if(DateTime.TryParse(Session["expiresAt"].S,out end)){TimeSpan left=end.ToUniversalTime()-DateTime.UtcNow;clockText.Text=left<=TimeSpan.Zero?"本手结束后结算":left.ToString(@"hh\:mm\:ss");}}if(actionClock!=null){if(paused){actionClock.Text="已暂停";return;}if(Hand["status"].S=="complete")actionClock.Text=reviewHold?"复盘中":"下一手 "+Math.Max(0,Math.Ceiling((settleAt-DateTime.UtcNow).TotalSeconds))+"s";else if(Hand["allInShowdown"].B&&Hand["runoutNextAt"].N>DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()){string next=Hand["street"].S=="flop"?"转牌":"河牌";actionClock.Text="ALL IN · "+next+" "+Math.Max(0,Math.Ceiling((Hand["runoutNextAt"].N-DateTimeOffset.UtcNow.ToUnixTimeMilliseconds())/1000))+"s";}else if(!Hand["legal"].Null){int seconds=(int)Math.Ceiling((Hand["actionDeadlineAt"].N-DateTimeOffset.UtcNow.ToUnixTimeMilliseconds())/1000),total=(int)Math.Max(1,Math.Ceiling((Hand["actionDeadlineAt"].N-Hand["actionStartedAt"].N)/1000));string key=Session["id"].S+"/"+Hand["number"].S+"/"+Hand["actionStartedAt"].S;if(key!=heroActionClockKey){heroActionClockKey=key;lastTickSecond=-1;PlayTurnPrompt();}actionClock.Text="行动剩余 "+Math.Max(0,seconds)+"s";if(seconds>0&&seconds<=Math.Ceiling(total/2d)&&seconds!=lastTickSecond){lastTickSecond=seconds;PlayClockTick();}}else actionClock.Text=busy&&state["ai"]["mode"].S=="external"?"AI 正在思考…":"等待牌友行动";}}
 int lastTickSecond=-1;string heroActionClockKey="";
 async void ToggleFastFold(){if(endingTable||paused||Session.Null||Hand["status"].S!="playing"||Hand["street"].S!="preflop"||Hero["folded"].B||!Hand["pending"].Items.Any(x=>x.I==0))return;fastFold=false;HideOverlay();await Run("action",Turn("action","fold","fastFold",true),true,true);bufferUntil=DateTime.UtcNow.AddSeconds(1);}
 void Render(){shell.RowDefinitions[1].Height=new GridLength(Session.Null?28:0);status.Visibility=Session.Null?Visibility.Visible:Visibility.Collapsed;body.Children.Clear();clockText=null;actionClock=null;body.LayoutTransform=new ScaleTransform(1,1);if(Session.Null){RenderLobby();}else {RenderTable();PlayEventSound();}UpdateClocks();}
 void SetFullscreen(bool value){WindowState=WindowState.Normal;WindowStyle=value?WindowStyle.None:WindowStyle.SingleBorderWindow;ResizeMode=value?ResizeMode.NoResize:ResizeMode.CanResize;WindowState=value?WindowState.Maximized:WindowState.Normal;}
 void RequestExit(){if(busy){Notice("正在保存当前行动，请稍候再退出。");return;}ShowGameConfirm("退出游戏","确定要退出 AfterHours 吗？\n当前进度会被安全保存。","退出",()=>Close());}
 void LoadPokerFaceAssets(){string custom=Path.Combine(root,"assets","cards","faces"),fallback=Path.Combine(root,"素材","图片","扑克牌");string folder=Directory.Exists(custom)&&Directory.GetFiles(custom).Count(file=>Path.GetExtension(file).Equals(".png",StringComparison.OrdinalIgnoreCase))==52?custom:fallback;if(!Directory.Exists(folder))return;foreach(string file in Directory.GetFiles(folder)){string extension=Path.GetExtension(file).ToLowerInvariant();if(extension==".png"||extension==".jpg"||extension==".jpeg")pokerFaceAssets[Path.GetFileNameWithoutExtension(file)]=file;}}
 string CardFacePath(string card){if(string.IsNullOrEmpty(card)||card.Length!=2)return "";string rank=card[0]=='T'?"10":card.Substring(0,1);string suit=card[1]=='s'?"黑桃":card[1]=='h'?"红桃":card[1]=='d'?"方片":card[1]=='c'?"草花":"";string path;return suit!=""&&pokerFaceAssets.TryGetValue(suit+"_"+rank,out path)?path:"";}
 ImageSource CardFace(string card){string path=CardFacePath(card);return path==""?null:Image(path);}
 ImageSource CardBack(){return Image(Path.Combine(root,"assets","cards","card-back.png"));}
 ImageSource Image(string path){ImageSource b;if(!bitmapCache.TryGetValue(path,out b)){b=UI.Bitmap(path);if(b!=null)bitmapCache[path]=b;}return b;}
 FrameworkElement Portrait(J player,double size){string path="";if(player["id"].S=="0"&&!string.IsNullOrEmpty(heroAvatar))path=heroAvatar;else if(player["id"].S=="0")path=Path.Combine(root,"assets","hero-default.jpg");else {string key=avatarMap[player["avatar"].S].S;if(key!="")path=Path.Combine(root,"assets","portraits",key);}var source=Image(path);var ellipse=new System.Windows.Shapes.Ellipse{Width=size,Height=size,Fill=source==null?(Brush)UI.Brush("#38455E"):new ImageBrush(source){Stretch=Stretch.UniformToFill},Stroke=UI.Brush("#727887"),StrokeThickness=2};if(source!=null)return ellipse;var g=new Grid{Width=size,Height=size};g.Children.Add(ellipse);var t=UI.Text(player["name"].S==""?"A":player["name"].S.Substring(0,1),size*.38);t.HorizontalAlignment=HorizontalAlignment.Center;g.Children.Add(t);return g;}
 void ShowOverlay(UIElement content,double width=980,double height=650){overlay.Children.Clear();overlay.Background=new SolidColorBrush(Color.FromArgb(228,0,8,6));var panel=UI.Box(content,UI.Brush("#081613"),18,new Thickness(25));panel.Width=Math.Min(width,Math.Max(620,ActualWidth-80));panel.Height=Math.Min(height,Math.Max(320,ActualHeight-100));panel.HorizontalAlignment=HorizontalAlignment.Center;panel.VerticalAlignment=VerticalAlignment.Center;panel.BorderBrush=UI.Brush("#5F8C7D");panel.BorderThickness=new Thickness(1.25);panel.Effect=new System.Windows.Media.Effects.DropShadowEffect{Color=Colors.Black,BlurRadius=28,ShadowDepth=8,Opacity=.72};overlay.Children.Add(panel);dialogCount=1;}
 void HideOverlay(){overlay.Children.Clear();overlay.Background=null;dialogCount=0;}
 void ShowGameMessage(string title,string message,Action afterClose=null){StackPanel p,f;var dialog=Dialog(title,out p,out f);var icon=UI.Text("◆",28,UI.Gold,true);icon.HorizontalAlignment=HorizontalAlignment.Center;p.Children.Add(icon);var body=UI.Text(message,17,UI.Ink);body.TextAlignment=TextAlignment.Center;body.TextWrapping=TextWrapping.Wrap;body.Margin=new Thickness(16,12,16,16);p.Children.Add(body);f.Children.Add(UI.Button("知道了",()=>{HideOverlay();if(afterClose!=null)afterClose();},145,true));ShowOverlay(dialog,620,330);}
 void ShowGameConfirm(string title,string message,string confirm,Action onConfirm,string cancel="取消"){StackPanel p,f;var dialog=Dialog(title,out p,out f);var icon=UI.Text("♠",32,UI.Gold,true);icon.HorizontalAlignment=HorizontalAlignment.Center;p.Children.Add(icon);var body=UI.Text(message,17,UI.Ink);body.TextWrapping=TextWrapping.Wrap;body.TextAlignment=TextAlignment.Center;body.Margin=new Thickness(16,12,16,16);p.Children.Add(body);f.Children.Add(UI.Button(cancel,HideOverlay,135));f.Children.Add(UI.Button(confirm,()=>{HideOverlay();onConfirm();},145,true));ShowOverlay(dialog,650,345);}
 Grid Dialog(string title,out StackPanel content,out StackPanel footer){var g=new Grid();g.RowDefinitions.Add(new RowDefinition{Height=new GridLength(64)});g.RowDefinitions.Add(new RowDefinition());g.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});var header=new Grid{Background=UI.Brush("#10231E")};header.ColumnDefinitions.Add(new ColumnDefinition());header.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(52)});var heading=UI.Text(title,25,UI.Ink,true);heading.VerticalAlignment=VerticalAlignment.Center;header.Children.Add(heading);var close=UI.Button("",HideOverlay,42);close.Content=UI.CloseIcon(18,UI.Ink);close.Padding=new Thickness(0);close.Margin=new Thickness(0,10,0,10);close.Background=UI.Brush("#0A1714");close.BorderBrush=UI.Brush("#42685C");close.ToolTip="关闭";Grid.SetColumn(close,1);header.Children.Add(close);var headerFrame=new Border{Child=header,BorderBrush=UI.Brush("#315349"),BorderThickness=new Thickness(0,0,0,1)};g.Children.Add(headerFrame);content=UI.Stack();content.Margin=new Thickness(8,14,8,14);var scroll=UI.Scroll(content);Grid.SetRow(scroll,1);g.Children.Add(scroll);footer=UI.Stack(true);footer.HorizontalAlignment=HorizontalAlignment.Right;footer.Margin=new Thickness(8,14,0,0);var footerFrame=new Border{Child=footer,BorderBrush=UI.Brush("#29483F"),BorderThickness=new Thickness(0,1,0,0)};Grid.SetRow(footerFrame,2);g.Children.Add(footerFrame);return g;}
 async Task PauseToggle(){if(endingTable||busy||Session.Null)return;bool next=!paused;await Run("pause",J.O("paused",next),false);paused=next;pauseAt=DateTime.UtcNow;HideOverlay();Render();}
 async Task EndCurrentTable(){if(endingTable||Session.Null)return;endingTable=true;fastFold=false;HideOverlay();try{await Run("end",Turn("reason","用户下桌"),true,true);}finally{endingTable=false;}}
 void ShowMenu(){StackPanel p,f;var d=Dialog("牌桌菜单",out p,out f);p.Children.Add(UI.Button(paused?"继续牌局":"暂停牌局",async()=>await PauseToggle()));p.Children.Add(UI.Button("补码 / 退码",ShowBank));p.Children.Add(UI.Button("本局精简复盘",async()=>{HideOverlay();reviewHold=Hand["status"].S=="complete";await ShowCompact();}));p.Children.Add(UI.Button("游戏设置",async()=>await ShowSettings()));p.Children.Add(UI.Button("音乐与音效",ShowMusic));p.Children.Add(UI.Button("游戏指南",ShowGuide));p.Children.Add(UI.Button("保存进度",async()=>{await Run("export",Turn());HideOverlay();}));p.Children.Add(UI.Button("结束本场 · 返回大厅",async()=>await EndCurrentTable()));ShowOverlay(d,800,680);}
 void ShowGuide(){StackPanel p,f;var d=Dialog("游戏指南",out p,out f);p.Children.Add(UI.Text("无限注德州扑克 · 52 张牌\n\n每人两张底牌，公共牌依次发出 3 / 1 / 1 张。从七张牌中选择最佳五张。\n\n加注金额是本轮累计投入；最小完整加注幅度按规则计算。短筹码全下不一定重新开放加注权。不同投入额拆分主池和边池，多余未跟注金额退回。\n\n牌型：同花顺 → 四条 → 葫芦 → 同花 → 顺子 → 三条 → 两对 → 一对 → 高牌。\n\nF：翻牌前快速弃牌，立即结束你的本手　F11：全屏　Esc：关闭面板\n\n精简复盘可从牌桌的 HANDS 或菜单主动打开；结束本场后，在大厅进入详细回放。完成至少一手并下桌后，可在牌友档案里判断本场对手身份。",17));ShowOverlay(d,850,640);}
}
}





