using System;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Threading;

namespace AfterHours {
public partial class MainWindow {
 J replayHand=new J(null),replayPlayers=new J(null);int replayIndex;Grid replayCanvas;TextBlock replayDescription,replayStep;Slider replaySlider;CheckBox revealCards;ListBox handList;ComboBox archiveList;DispatcherTimer replayTimer;string replaySession="";int replayLoadVersion;ListBox trajectory;int highlightPlayer=-1;
 void ShowCompact(bool inline=false){if(Hand["status"].S!="complete"){Notice("当前手牌结束后才有精简复盘。");return;}var panel=UI.Stack();var top=UI.Stack(true);top.Children.Add(UI.Text("牌局 #"+Hand["number"].S+"   POT "+UI.Money(Hand["pot"].N),21,null,true));var close=UI.Button(inline?"收起":"关闭",()=>{if(compactContainer!=null)compactContainer.Visibility=Visibility.Collapsed;HideOverlay();reviewHold=false;settleAt=DateTime.UtcNow.AddSeconds(5);},90);top.Children.Add(close);panel.Children.Add(top);var header=UI.Stack(true);foreach(var h in new[]{"牌友 / 底牌","翻牌前","翻牌","转牌","河牌","净盈亏"}){var t=UI.Text(h,12,UI.Muted);t.Width=h=="牌友 / 底牌"?230:h=="净盈亏"?105:145;header.Children.Add(t);}panel.Children.Add(header);
  foreach(J result in Hand["results"].Items){J p=Session["players"].Items.FirstOrDefault(x=>x["id"].I==result["playerId"].I)??new J(null);var row=UI.Stack(true);row.Margin=new Thickness(0,8,0,3);var who=UI.Stack(true);who.Width=230;var bio=UI.Stack();bio.Width=90;bio.Children.Add(Portrait(p,45));bio.Children.Add(UI.Text(p["name"].S,12));who.Children.Add(bio);var hole=UI.Stack();string[] best=result["rank"]["cards"].Items.Select(x=>x.S).ToArray();hole.Children.Add(Cards(result["hole"].Items,34,best,2));hole.Children.Add(UI.Text(result["rank"].Null?(result["folded"].B?"已弃牌":"未摊牌"):result["rank"]["name"].S,11,UI.Gold));who.Children.Add(hole);row.Children.Add(who);string[] streets={"preflop","flop","turn","river"};foreach(string street in streets){var cell=UI.Stack();cell.Width=145;var cards=Hand["board"].Items.Skip(street=="turn"?3:street=="river"?4:0).Take(street=="preflop"?0:street=="flop"?3:1);cell.Children.Add(Cards(cards,31,best));string action=string.Join(" / ",Hand["events"].Items.Where(e=>e["playerId"].I==p["id"].I&&!e["playerId"].Null&&e["street"].S==street&&(e["type"].S=="action"||e["type"].S=="blind")).Select(e=>e["type"].S=="blind"?"盲注 "+e["amount"].S:UI.ActionName(e["action"].S)+(e["amount"].N>0?" "+e["amount"].S:"")));cell.Children.Add(UI.Text(action==""?"—":action,11,UI.Muted));row.Children.Add(cell);}var totals=UI.Stack();totals.Width=105;totals.Children.Add(UI.Text((result["net"].N>0?"+":"")+result["net"].S,23,result["net"].N>0?UI.Brush("#F44365"):UI.Brush("#41CDA0"),true));totals.Children.Add(UI.Text("投入 "+result["invested"].S,11,UI.Muted));row.Children.Add(totals);panel.Children.Add(row);}
  panel.Children.Add(UI.Text("金色边缘标出实际成牌的五张牌；完整行动轨迹请下桌后到大厅查看。",12,UI.Muted));if(inline){compactContainer=new Grid{Width=1020,MaxHeight=560};var box=UI.Box(UI.Scroll(panel),UI.Brush("#0C1917"),12,new Thickness(18));box.BorderBrush=UI.Brush("#557A6D");box.BorderThickness=new Thickness(1);compactContainer.Children.Add(box);UI.At(table,compactContainer,240,165);}else{ShowOverlay(UI.Scroll(panel),1100,720);reviewHold=true;}
 }
 async Task ShowReplay(){if(!Session.Null){reviewHold=true;ShowCompact();return;}HideOverlay();StackPanel unused,footer;var d=Dialog("详细牌局复盘",out unused,out footer);var frame=new Grid();frame.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(220)});frame.ColumnDefinitions.Add(new ColumnDefinition());frame.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(235)});frame.RowDefinitions.Add(new RowDefinition{Height=new GridLength(54)});frame.RowDefinitions.Add(new RowDefinition());frame.RowDefinitions.Add(new RowDefinition{Height=new GridLength(110)});
  archiveList=UI.Combo(new string[0],-1,350);Grid.SetColumnSpan(archiveList,3);frame.Children.Add(archiveList);handList=new ListBox{Background=UI.Brush("#0B1513"),Foreground=UI.Ink,BorderThickness=new Thickness(0),Margin=new Thickness(0,5,14,5),FontSize=15};Grid.SetRow(handList,1);frame.Children.Add(handList);replayCanvas=new Grid{Background=UI.Brush("#0E241D"),Margin=new Thickness(0,5,0,5)};Grid.SetColumn(replayCanvas,1);Grid.SetRow(replayCanvas,1);frame.Children.Add(replayCanvas);trajectory=new ListBox{Background=UI.Brush("#0D1916"),Foreground=UI.Ink,BorderThickness=new Thickness(0),Margin=new Thickness(10,5,0,5)};trajectory.SelectionChanged+=(s,e)=>{if(trajectory.SelectedIndex>=0&&trajectory.SelectedIndex!=replayIndex)SetReplay(trajectory.SelectedIndex);};Grid.SetColumn(trajectory,2);Grid.SetRow(trajectory,1);frame.Children.Add(trajectory);var controls=UI.Stack();var buttons=UI.Stack(true);buttons.Children.Add(UI.Button("|◀",()=>SetReplay(0),55));buttons.Children.Add(UI.Button("上一步",()=>SetReplay(replayIndex-1),95));buttons.Children.Add(UI.Button("播放 / 暂停",()=>{if(replayTimer==null){replayTimer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(950)};replayTimer.Tick+=(s,e)=>{if(dialogCount==0||replayIndex>=replayHand["events"].Items.Count()-1){replayTimer.Stop();return;}SetReplay(replayIndex+1);};}if(replayTimer.IsEnabled)replayTimer.Stop();else replayTimer.Start();},130,true));buttons.Children.Add(UI.Button("下一步",()=>SetReplay(replayIndex+1),95));buttons.Children.Add(UI.Button("▶|",()=>SetReplay(int.MaxValue),55));revealCards=UI.Check("显示所有底牌");revealCards.Click+=(s,e)=>SetReplay(replayIndex);buttons.Children.Add(revealCards);replayStep=UI.Text("",13,UI.Muted);buttons.Children.Add(replayStep);controls.Children.Add(buttons);replaySlider=new Slider{Minimum=0,Maximum=1,IsSnapToTickEnabled=true,TickFrequency=1,Margin=new Thickness(12,6,12,5)};replaySlider.ValueChanged+=(s,e)=>{if((int)e.NewValue!=replayIndex)SetReplay((int)e.NewValue);};controls.Children.Add(replaySlider);replayDescription=UI.Text("请选择历史场次与手牌。",13,UI.Muted);controls.Children.Add(replayDescription);Grid.SetRow(controls,2);Grid.SetColumnSpan(controls,3);frame.Children.Add(controls);var outer=(ScrollViewer)d.Children[1];outer.Content=frame;outer.VerticalScrollBarVisibility=ScrollBarVisibility.Disabled;ShowOverlay(d,1380,800);
  J archives=await rules.Call("archives");foreach(var entry in archives["sessions"].Items)archiveList.Items.Add(new ComboBoxItem{Content=entry["label"].S+"  ·  "+entry["hands"].S+" 手",Tag=entry["id"].S});archiveList.SelectionChanged+=async(s,e)=>{var item=archiveList.SelectedItem as ComboBoxItem;if(item==null)return;replaySession=(string)item.Tag;int version=++replayLoadVersion;J result=await rules.Call("archive?session="+Uri.EscapeDataString(replaySession));if(version!=replayLoadVersion)return;handList.Items.Clear();foreach(J hand in result["hands"].Items)handList.Items.Add(new ListBoxItem{Content="#"+hand["number"].S+"    "+(hand["net"].N>=0?"+":"")+UI.Money(hand["net"].N),Tag=hand["number"].I,Padding=new Thickness(8,14,8,14)});if(handList.Items.Count>0)handList.SelectedIndex=0;};handList.SelectionChanged+=async(s,e)=>{var item=handList.SelectedItem as ListBoxItem;if(item==null)return;if(replayTimer!=null)replayTimer.Stop();int version=++replayLoadVersion;J result=await rules.Call("history?session="+Uri.EscapeDataString(replaySession)+"&hand="+item.Tag);if(version!=replayLoadVersion)return;replayHand=result["hand"];replayPlayers=result["players"];replayIndex=-1;trajectory.Items.Clear();foreach(J evt in replayHand["events"].Items){var line=UI.Text((evt["seq"].I+1)+" · "+UI.Street(evt["street"].S)+"\n"+evt["text"].S,12);line.Width=188;line.Margin=new Thickness(4,7,4,7);trajectory.Items.Add(line);}replaySlider.Maximum=Math.Max(0,replayHand["events"].Items.Count()-1);SetReplay(0);};if(archiveList.Items.Count>0)archiveList.SelectedIndex=0;else replayDescription.Text="还没有结束的场次。完成牌局并下桌后即可回放。";
 }
 void SetReplay(int index){if(replayHand.Null)return;J[] events=replayHand["events"].Items.ToArray();if(events.Length==0)return;replayIndex=Math.Max(0,Math.Min(events.Length-1,index));replaySlider.Value=replayIndex;if(trajectory!=null&&trajectory.SelectedIndex!=replayIndex)trajectory.SelectedIndex=replayIndex;J ev=events[replayIndex],snapshot=ev["snapshot"];double shownPot=ev["type"].S=="result"?replayHand["finalPot"].N:snapshot["pot"].N;replayStep.Text=(replayIndex+1)+" / "+events.Length;replayCanvas.Children.Clear();var content=new Grid();content.RowDefinitions.Add(new RowDefinition{Height=new GridLength(128)});content.RowDefinitions.Add(new RowDefinition());content.RowDefinitions.Add(new RowDefinition{Height=new GridLength(80)});var top=UI.Stack();top.HorizontalAlignment=HorizontalAlignment.Center;top.Children.Add(UI.Text(UI.Street(ev["street"].S)+"   ·   "+ev["type"].S+"   ·   POT "+UI.Money(shownPot),18,null,true));top.Children.Add(Cards(ev["board"].Items,48,null,5));content.Children.Add(top);
  var rows=UI.Stack();foreach(J ps in snapshot["players"].Items){J player=replayPlayers.Items.FirstOrDefault(x=>x["id"].I==ps["id"].I)??new J(null);J result=replayHand["results"].Items.FirstOrDefault(x=>x["playerId"].I==ps["id"].I)??new J(null);var row=UI.Stack(true);row.Margin=new Thickness(8,5,8,5);row.Children.Add(Portrait(player,42));var name=UI.Text(player["name"].S,15,null,true);name.Width=80;name.Margin=new Thickness(10,0,0,0);row.Children.Add(name);bool shown=revealCards.IsChecked==true||ps["id"].I==0||(replayIndex>=events.Length-1&&replayHand["showdown"].B&&!result["folded"].B)||events.Take(replayIndex+1).Any(x=>x["type"].S=="show"&&x["playerId"].I==ps["id"].I);IEnumerable<J> hole=shown?result["hole"].Items:Enumerable.Empty<J>();row.Children.Add(Cards(hole,30,highlightPlayer==ps["id"].I?result["rank"]["cards"].Items.Select(c=>c.S):null,2));var amounts=UI.Text("筹码 "+UI.Money(ps["stack"].N)+"   本轮 "+UI.Money(ps["streetBet"].N)+"   总投入 "+UI.Money(ps["totalBet"].N),13);amounts.Width=195;amounts.Margin=new Thickness(8,0,8,0);row.Children.Add(amounts);row.Children.Add(UI.Text(ps["folded"].B?"弃牌":ps["allIn"].B?"ALL IN":ps["lastAction"].S,13,UI.Gold));var border=UI.Box(row,!ev["playerId"].Null&&ev["playerId"].I==ps["id"].I?UI.Brush("#29416A"):UI.Brush("#1F2B32"),6,new Thickness(4));border.Margin=new Thickness(7,2,7,2);if(shown){border.Cursor=System.Windows.Input.Cursors.Hand;border.MouseLeftButtonUp+=(s,e)=>{highlightPlayer=ps["id"].I;SetReplay(replayIndex);};border.MouseEnter+=(s,e)=>{top.Children.Clear();top.Children.Add(UI.Text(UI.Street(ev["street"].S)+" · POT "+UI.Money(shownPot),18));top.Children.Add(Cards(ev["board"].Items,48,result["rank"]["cards"].Items.Select(c=>c.S),5));};}rows.Children.Add(border);}var rowScroll=UI.Scroll(rows);Grid.SetRow(rowScroll,1);content.Children.Add(rowScroll);string pots=replayIndex==events.Length-1?string.Join("   ",replayHand["pots"].Items.Select(x=>x["name"].S+" "+UI.Money(x["amount"].N))):"主池与边池在结算步骤显示";string burned=revealCards.IsChecked==true?string.Join(" ",replayHand["burned"].Items.Select(x=>x.S)):"勾选显示所有底牌后查看";var audit=UI.Text(pots+"\n烧牌："+burned+"\n"+ev["text"].S,13,UI.Gold);audit.Margin=new Thickness(14);Grid.SetRow(audit,2);content.Children.Add(audit);replayCanvas.Children.Add(content);replayDescription.Text="事件 "+ev["seq"].S+"  ·  "+ev["time"].S+"   "+ev["text"].S;
 }
}
}


