using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Security.Cryptography;
using System.Text;
using Microsoft.Win32;

namespace AfterHours {
public partial class MainWindow {
 async Task ShowSettings(){J settings=await rules.Call("ai-settings");StackPanel p,f;var dialog=Dialog("游戏设置",out p,out f);var mode=UI.Combo(new[]{"本地机器人","外部 AI"},settings["mode"].S=="external"?1:0,240);mode.IsEnabled=Session.Null;p.Children.Add(Field("对手控制方式",mode));var url=UI.Input(settings["baseUrl"].S);var model=UI.Input(settings["model"].S);var key=new PasswordBox{MinHeight=38,FontSize=16,Padding=new Thickness(10),Background=UI.Brush("#11151E"),Foreground=UI.Ink,Margin=new Thickness(0,6,0,10)};p.Children.Add(Field("API 地址（支持本机模型或 HTTPS）",url));p.Children.Add(Field("模型名",model));p.Children.Add(Field(settings["hasKey"].B?"API Key（已加密保存，留空保留）":"API Key",key));var clear=UI.Check("清除已保存的 Key");p.Children.Add(clear);int[] waits={5,10,20,30,60,90,120};var timeout=UI.Combo(waits.Select(x=>x+" 秒"),Array.IndexOf(waits,settings["timeoutSeconds"].I),200);if(timeout.SelectedIndex<0)timeout.SelectedIndex=3;p.Children.Add(Field("最长等待",timeout));p.Children.Add(UI.Text("超时、断线或非法动作将由本地策略接管。密钥通过 Windows DPAPI 加密，牌谱不会记录密钥。",13,UI.Muted));
  Func<object> aiBody=()=>{string entered=key.Password.Trim();string encrypted=entered!=""?"dpapi:"+Convert.ToBase64String(ProtectedData.Protect(Encoding.UTF8.GetBytes(entered),null,DataProtectionScope.CurrentUser)):null;var d=J.O("mode",mode.SelectedIndex==0?"local":"external","baseUrl",url.Text.Trim(),"model",model.Text.Trim(),"apiKey",entered,"clearKey",clear.IsChecked==true,"timeoutSeconds",waits[timeout.SelectedIndex]);if(clear.IsChecked==true)d["encryptedKey"]="";else if(encrypted!=null)d["encryptedKey"]=encrypted;return d;};p.Children.Add(UI.Button("测试连接",async()=>{if(busy)return;busy=true;try{J r=await rules.Call("ai-test",aiBody());Notice("连接成功 · "+r["elapsedMs"].S+" ms · "+r["action"].S);ShowGameMessage("连接测试","连接成功，模型返回合法行动。");}catch(Exception e){Notice(e.Message);ShowGameMessage("连接测试",e.Message);}finally{busy=false;}}));
  var avatarRow=UI.Stack(true);avatarRow.Children.Add(Portrait(new J(J.O("id",0,"name","你")),58));avatarRow.Children.Add(UI.Button("上传我的头像",()=>{var picker=new OpenFileDialog{Filter="头像图片|*.png;*.jpg;*.jpeg;*.webp",Title="选择我的头像"};if(picker.ShowDialog(this)!=true)return;try{var info=new FileInfo(picker.FileName);if(info.Length>5*1024*1024)throw new Exception("头像不能超过 5 MB");string dest=Path.Combine(dataRoot,".poker-data","player-avatar.png");Directory.CreateDirectory(Path.GetDirectoryName(dest));var img=UI.Bitmap(picker.FileName);var encoder=new System.Windows.Media.Imaging.PngBitmapEncoder();encoder.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(img));using(var stream=File.Create(dest))encoder.Save(stream);heroAvatar=dest;bitmapCache.Remove(dest);SavePreferences();Notice("头像已保存");}catch(Exception ex){ShowGameMessage("头像",ex.Message);}}));avatarRow.Children.Add(UI.Button("恢复默认头像",()=>{heroAvatar="";SavePreferences();}));p.Children.Add(avatarRow);var gender=UI.Combo(new[]{"男声","女声"},state["profile"]["gender"].S=="f"?1:0,160);p.Children.Add(Field("玩家行动语音",gender));var font=UI.Combo(new[]{"90%","100%","110%","120%"},Math.Max(0,(int)Math.Round((fontScale-.9)*10)),160);p.Children.Add(Field("界面字号",font));p.Children.Add(UI.Button("切换无边框全屏 / 窗口",()=>SetFullscreen(WindowStyle!=WindowStyle.None)));f.Children.Add(UI.Button("保存设置",async()=>{if(busy)return;busy=true;try{await rules.Call("ai-settings",aiBody());state=await rules.Call("profile-settings",J.O("gender",gender.SelectedIndex==0?"m":"f"));fontScale=.9+font.SelectedIndex*.1;UI.Scale=fontScale;FontSize=14*fontScale;SavePreferences();HideOverlay();Render();Notice("设置已保存");}catch(Exception e){ShowGameMessage("设置",e.Message);}finally{busy=false;}},160,true));ShowOverlay(dialog,920,790);}
 async Task ShowContacts(){J contacts=await rules.Call("contacts");StackPanel p,f;var dialog=Dialog("牌友档案",out p,out f);var search=UI.Input("");p.Children.Add(Field("搜索牌友姓名",search));var results=UI.Stack();p.Children.Add(results);Action render=()=>{results.Children.Clear();foreach(J player in contacts["players"].Items.Where(x=>x["name"].S.IndexOf(search.Text,StringComparison.OrdinalIgnoreCase)>=0)){var row=UI.Stack(true);row.Children.Add(Portrait(player,52));var label=UI.Stack();label.Width=400;label.Margin=new Thickness(16,0,0,0);label.Children.Add(UI.Text(player["name"].S,18,null,true));J world=state["world"]["players"].Items.FirstOrDefault(x=>x["characterId"].S==player["characterId"].S)??new J(null);label.Children.Add(UI.Text(world["status"].S+" · "+world["activity"].S+" · "+(player["discovery"]["revealed"].B?state["styles"][player["style"].S]["name"].S:"身份未公开"),13,UI.Muted));row.Children.Add(label);row.Children.Add(UI.Button(player["guessEligible"].B?"查看 / 判断身份":"查看档案",()=>ShowPlayer(player),170));var box=UI.Box(row);box.Margin=new Thickness(0,4,0,4);results.Children.Add(box);}};search.TextChanged+=(s,e)=>render();render();ShowOverlay(dialog,980,770);}
 void ShowPlayer(J player){StackPanel p,f;var d=Dialog(player["name"].S+" · 牌友档案",out p,out f);p.Children.Add(Portrait(player,85));J stats=player["stats"];double hands=Math.Max(1,stats["hands"].N);p.Children.Add(UI.Text("VPIP  "+(stats["vpip"].N/hands*100).ToString("0.0")+"%     PFR  "+(stats["pfr"].N/hands*100).ToString("0.0")+"%",24,null,true));p.Children.Add(UI.Text("生涯手数 "+stats["hands"].S+"   ·   单手最高赢额 "+UI.Money(stats["maxWon"].N),15,UI.Muted));p.Children.Add(UI.Text("决策风格参数已用于塑造该角色的牌桌行为，具体数值不公开。",13,UI.Muted));string[] codes={"TAG","TP","LAG","LP","NIT","MANIAC","GRINDER"};var mark=UI.Combo(new[]{"未标记"}.Concat(codes.Select(x=>state["styles"][x]["name"].S)),0,240);string old=state["profile"]["marks"][player["characterId"].S].S;mark.SelectedIndex=Math.Max(0,Array.IndexOf(codes,old)+1);p.Children.Add(Field("我的预估形象（不提交竞猜）",mark));p.Children.Add(UI.Button("保存标记",async()=>{await Run("mark",J.O("characterId",player["characterId"].S,"mark",mark.SelectedIndex==0?"":codes[mark.SelectedIndex-1]),false);Notice("预估形象已保存");}));if(player["discovery"]["previousGuesses"].Items.Any())p.Children.Add(UI.Text("曾经判断："+string.Join(" / ",player["discovery"]["previousGuesses"].Items.Select(x=>state["styles"][x.S]["name"].S)),15,UI.Gold));foreach(J part in player["dossier"].Items){var label=UI.Text(part["label"].S,17,null,true);label.Margin=new Thickness(0,15,0,6);p.Children.Add(label);p.Children.Add(UI.Text(part["locked"].B?"档案尚未解锁":part["text"].S,15,part["locked"].B?UI.Muted:UI.Ink));}if(!player["memory"].Null)p.Children.Add(UI.Text("共同经历\n"+Readable(player["memory"]),14,UI.Muted));if(Session.Null&&player["guessEligible"].B){var guess=UI.Combo(codes.Select(x=>state["styles"][x]["name"].S),0,200);f.Children.Add(guess);f.Children.Add(UI.Button("提交本场身份判断",async()=>{await Run("guess",J.O("sessionId",state["lastSummary"]["id"].S,"characterId",player["characterId"].S,"style",codes[guess.SelectedIndex]),false);HideOverlay();await ShowContacts();},220,true));}ShowOverlay(d,940,760);}
 string Readable(J value){if(value.Null)return "暂无共同记忆";if(value.Value is string)return value.S;if(value.Items.Any())return string.Join("\n",value.Items.Select(x=>!x["text"].Null?x["text"].S:!x["summary"].Null?x["summary"].S:Readable(x)));var dict=value.Value as IDictionary<string,object>;if(dict!=null)return string.Join("\n",dict.Where(x=>x.Key!="observer"&&x.Key!="traits").Select(x=>x.Key+"："+Readable(new J(x.Value))));return value.S;}
}
}

