using System;
using System.Linq;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Documents;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Shapes;
using System.Windows.Threading;

namespace AfterHours {
public partial class MainWindow {
 const double TableWidth=1500,TableHeight=773.4375,TableCardScale=1.2;
 TextBlock avatarCountdown;System.Windows.Shapes.Path countdownArc;int countdownSeat=-1;string botVisualCountdownKey="";double botVisualCountdownStartedAt;
 Slider betSlider;TextBox betInput;Button raiseButton,extendButton,compactReviewButton;bool syncingBet;
 Canvas animationLayer;int showdownHighlightPlayer=-1,renderedEventSeq=-1,renderedBoardCount;string payoutAnimationKey="";Dictionary<string,List<FrameworkElement>> showdownCardViews=new Dictionary<string,List<FrameworkElement>>();
 async void ShowTableNotice(string text){if(table==null)return;var parent=table;var t=TableText(text,14);t.TextAlignment=TextAlignment.Center;var notice=UI.Box(t,UI.Brush("#252B36"),6,new Thickness(16,8,16,8));notice.MaxWidth=600;notice.Measure(new Size(600,100));UI.At(parent,notice,750-notice.DesiredSize.Width/2,15);await System.Threading.Tasks.Task.Delay(4000);parent.Children.Remove(notice);}
 // Coordinates measured against the supplied 3840 x 1980 reference, in a 1500-unit viewport.
 readonly double[,] seatAnchors={{661,560},{991,491},{1078,295},{1015,142},{667,75},{315,142},{254,295}};
 readonly double[,] betAnchors={{714,438},{947,438},{1007,326},{999,230},{704,218},{538,230},{485,326}};
 readonly double[,] dealerAnchors={{850,574},{1034,443},{1082,394},{998,282},{787,190},{481,282},{437,394}};
 int[] SeatSlots(int count){switch(count){case 2:return new[]{0,4};case 3:return new[]{0,3,5};case 4:return new[]{0,2,4,6};case 5:return new[]{0,2,3,5,6};case 6:return new[]{0,1,2,3,5,6};default:return new[]{0,1,2,3,4,5,6};}}
 TextBlock TableText(string text,double size,Brush color=null,bool bold=false){var t=UI.Text(text,size,color,bold);t.FontFamily=new FontFamily("Microsoft YaHei UI");t.FontSize=size;return t;}
 string Chips(double n){return n.ToString("0.##",System.Globalization.CultureInfo.InvariantCulture);}
 Button TableButton(string text,Action click,double width,double height,bool blue=false){var b=UI.Button(text,click,width,blue);b.Margin=new Thickness(0);b.Height=height;b.MinHeight=0;b.Padding=new Thickness(4);b.FontSize=16;b.BorderBrush=UI.Brush(blue?"#52D9A7":"#40554F");b.Background=new LinearGradientBrush(UI.Brush(blue?"#159869":"#1A2825").Color,UI.Brush(blue?"#06442F":"#0B1211").Color,90);if(blue)b.Effect=new DropShadowEffect{Color=Colors.Black,BlurRadius=7,ShadowDepth=3,Opacity=.55};return b;}
 Button CompactReviewButton(){var b=TableButton("",async()=>await ShowCompact(),48,46);b.Background=new SolidColorBrush(Color.FromArgb(52,2,16,13));b.BorderBrush=UI.Brush("#476B60");b.BorderThickness=new Thickness(1);b.ToolTip="本局精简复盘 · 浏览任意手牌";var icon=new Canvas{Width=30,Height=29,ClipToBounds=false,IsHitTestVisible=false};var first=TableCard("As",18);first.RenderTransform=new RotateTransform(-7,9,14);var second=TableCard("Ah",18);second.RenderTransform=new RotateTransform(7,9,14);UI.At(icon,first,2,2);UI.At(icon,second,11,1);Panel.SetZIndex(second,1);b.Content=icon;return b;}
 FrameworkElement CurrencyIcon(double size=13){var c=new Canvas{Width=size,Height=size};var p=new Polygon{Stroke=UI.Brush("#42B699"),StrokeThickness=1.4,Fill=Brushes.Transparent};for(int i=0;i<6;i++){double a=(i*60-30)*Math.PI/180;p.Points.Add(new Point(size/2+Math.Cos(a)*(size/2-1),size/2+Math.Sin(a)*(size/2-1)));}c.Children.Add(p);var inner=new Polygon{Stroke=UI.Brush("#42B699"),StrokeThickness=1,Fill=Brushes.Transparent};for(int i=0;i<6;i++){double a=(i*60-30)*Math.PI/180;inner.Points.Add(new Point(size/2+Math.Cos(a)*size*.22,size/2+Math.Sin(a)*size*.22));}c.Children.Add(inner);return c;}
 FrameworkElement ChipStack(int count=3,double size=24){int stage=Math.Max(1,Math.Min(3,count));var source=Image(System.IO.Path.Combine(root,"assets","chips","casino-chip-"+stage+".png"));if(source!=null)return new System.Windows.Controls.Image{Source=source,Width=size,Height=size,Stretch=Stretch.Uniform,SnapsToDevicePixels=true};var c=new Canvas{Width=size*.74,Height=size};for(int i=0;i<stage;i++){var g=new Canvas{Width=size*.68,Height=size*.68};g.Children.Add(new Ellipse{Width=size*.68,Height=size*.68,Fill=UI.Brush("#B9232C"),Stroke=UI.Brush("#751014"),StrokeThickness=1.2});g.Children.Add(new Ellipse{Width=size*.30,Height=size*.30,Margin=new Thickness(size*.19),Fill=UI.Brush("#F6E5D0"),Stroke=UI.Brush("#8E151D"),StrokeThickness=1});UI.At(c,g,0,size*.32-i*size*.16);}return c;}
 Border CardGlow(double width,double height){var glow=new Border{Tag="showdown-glow",Width=width,Height=height,CornerRadius=new CornerRadius(5),BorderBrush=UI.Brush("#FFD36C"),BorderThickness=new Thickness(2.4),IsHitTestVisible=false,Effect=new DropShadowEffect{Color=Color.FromRgb(255,193,72),BlurRadius=13,ShadowDepth=0,Opacity=.95}};Panel.SetZIndex(glow,100);return glow;}
 void RegisterShowdownCard(string value,FrameworkElement visual){if(value.Length!=2)return;List<FrameworkElement> cards;if(!showdownCardViews.TryGetValue(value,out cards)){cards=new List<FrameworkElement>();showdownCardViews[value]=cards;}cards.Add(visual);}
 void ApplyShowdownHighlights(int id){foreach(FrameworkElement visual in showdownCardViews.SelectMany(pair=>pair.Value)){var canvas=visual as Canvas;if(canvas==null)continue;foreach(Border glow in canvas.Children.OfType<Border>().Where(child=>(child.Tag as string)=="showdown-glow").ToArray())canvas.Children.Remove(glow);}foreach(string card in BestCardsFor(id)){List<FrameworkElement> visuals;if(!showdownCardViews.TryGetValue(card,out visuals))continue;foreach(FrameworkElement visual in visuals){var canvas=visual as Canvas;if(canvas!=null)canvas.Children.Add(CardGlow(canvas.Width,canvas.Height));}}}
 FrameworkElement TableCard(string value,double width,bool highlight=false){bool back=string.IsNullOrEmpty(value)||value=="??";string rank=back?"":value[0]=='T'?"10":value.Substring(0,1);string suit=back?"":value.Substring(1,1);string symbol=suit=="s"?"♠":suit=="h"?"♥":suit=="d"?"♦":"♣";string fill=back?"#424B5C":suit=="c"?"#26AA4B":suit=="d"?"#2779C6":suit=="h"?"#D84453":"#3B424D";double height=width*(back?1.42:1.52);var canvas=new Canvas{Width=width,Height=height,Clip=new RectangleGeometry(new Rect(0,0,width,height),5,5),UseLayoutRounding=true,SnapsToDevicePixels=true};canvas.Children.Add(new Border{Width=width,Height=height,CornerRadius=new CornerRadius(5),Background=new LinearGradientBrush(UI.Brush(fill).Color,UI.Brush(back?"#343D4D":fill).Color,90),BorderBrush=UI.Brush(back?"#A0A4B0":fill),BorderThickness=new Thickness(back?2:0)});ImageSource artwork=back?CardBack():CardFace(value);if(artwork!=null){var image=new System.Windows.Controls.Image{Source=artwork,Width=width,Height=height,Stretch=Stretch.Fill,UseLayoutRounding=true,SnapsToDevicePixels=true};RenderOptions.SetBitmapScalingMode(image,BitmapScalingMode.HighQuality);canvas.Children.Add(image);}else if(back){for(double x=-width;x<width*2;x+=12){for(double y=-9;y<height;y+=9){var line=new Polyline{Stroke=UI.Brush("#7B8494"),StrokeThickness=1.6,Points=new PointCollection{new Point(x,y),new Point(x+6,y+6),new Point(x+12,y)}};canvas.Children.Add(line);}}}else{var r=TableText(rank,width*.72,Brushes.White);r.FontFamily=new FontFamily("Bahnschrift SemiCondensed");r.FontWeight=FontWeights.Light;r.LineHeight=width*.65;UI.At(canvas,r,5,-1);var s=TableText(symbol,width*.38,Brushes.White);s.FontFamily=new FontFamily("Segoe UI Symbol");UI.At(canvas,s,6,width*.58);var large=TableText(symbol,width*.75,Brushes.White);large.FontFamily=new FontFamily("Segoe UI Symbol");UI.At(canvas,large,width*.30,width*.94);}if(highlight)canvas.Children.Add(CardGlow(width,height));return canvas;}
  FrameworkElement HoleFan(J player,bool hero,HashSet<string> highlights=null,bool winner=false,bool dim=false){double scale=(winner?1.3:1)*TableCardScale,width=(hero?55:44)*scale,spacing=(hero?42:39)*scale;var c=new Canvas{Width=(hero?103:87)*scale,Height=width*1.52,Opacity=dim?.42:1};var cards=player["hole"].Items.Select(x=>x.S).Take(2).ToList();while(cards.Count<2)cards.Add("");for(int i=0;i<2;i++){var card=TableCard(cards[i],width,highlights!=null&&highlights.Contains(cards[i]));RegisterShowdownCard(cards[i],card);card.RenderTransform=new RotateTransform(i==0?-7:7,width/2,width*1.3);UI.At(c,card,i*spacing,i==0?0:scale);}if(dim){var shade=new Border{Width=c.Width,Height=c.Height,Background=new SolidColorBrush(Color.FromArgb(72,0,0,0)),IsHitTestVisible=false};UI.At(c,shade,0,0);}return c;}
 string ActionLabel(J p){string a=p["lastAction"].S;if(p["status"].S=="empty"||p["status"].S=="busted")return "空座";if(p["status"].S=="sittingOut")return "暂离";if(p["allIn"].B)return "全下";if(a.StartsWith("Straddle"))return "STRADDLE";if(a.StartsWith("小盲"))return "SB";if(a.StartsWith("大盲"))return "BB";if(a.StartsWith("加注"))return "加注";if(a.StartsWith("跟注"))return "跟注";if(a.StartsWith("下注"))return "下注";if(a.StartsWith("过牌"))return "过牌";if(a.StartsWith("弃牌"))return "弃牌";return a;}
 J ResultForPlayer(int id){return Hand["results"].Items.FirstOrDefault(x=>x["playerId"].I==id)??new J(null);}
 double? AllInEquity(int id){if(!Hand["allInShowdown"].B)return null;J equity=Hand["equities"].Items.FirstOrDefault(x=>x["playerId"].I==id)??new J(null);return equity.Null?null:(double?)equity["percent"].N;}
 FrameworkElement AllInEquityBadge(int id){double? value=AllInEquity(id);if(!value.HasValue)return null;double percent=Math.Max(0,Math.Min(100,value.Value)),start=-Math.PI/2,end=start+Math.PI*2*percent/100;var c=new Canvas{Width=44,Height=29,ToolTip="全下胜率 · 基于未知牌的模拟结果"};c.Children.Add(new Ellipse{Width=27,Height=27,Fill=UI.Brush("#102821"),Stroke=UI.Brush("#395D51"),StrokeThickness=2});Point from=new Point(13.5+Math.Cos(start)*10,13.5+Math.Sin(start)*10),to=new Point(13.5+Math.Cos(end)*10,13.5+Math.Sin(end)*10);var figure=new PathFigure{StartPoint=from};figure.Segments.Add(new ArcSegment(to,new Size(10,10),0,percent>50,SweepDirection.Clockwise,true));var geometry=new PathGeometry();geometry.Figures.Add(figure);c.Children.Add(new System.Windows.Shapes.Path{Data=geometry,Stroke=UI.Brush(percent>=50?"#59E0A2":"#E9A85A"),StrokeThickness=3,StrokeStartLineCap=PenLineCap.Round,StrokeEndLineCap=PenLineCap.Round});var label=TableText(Math.Round(percent).ToString()+"%",10,UI.Brush("#F4F7F2"),true);label.Width=42;label.TextAlignment=TextAlignment.Center;UI.At(c,label,1,7);return c;}
 HashSet<string> BestCardsFor(int id){var cards=new HashSet<string>();if(Hand["status"].S!="complete"||!Hand["showdown"].B)return cards;foreach(J c in ResultForPlayer(id)["rank"]["cards"].Items)if(c.S.Length==2)cards.Add(c.S);return cards;}
 string ShowdownRank(int id){if(Hand["status"].S!="complete"||!Hand["showdown"].B)return "";return ResultForPlayer(id)["rank"]["name"].S;}
 void SetShowdownHighlight(int id){if(Hand["status"].S!="complete"||!Hand["showdown"].B||showdownHighlightPlayer==id)return;showdownHighlightPlayer=id;ApplyShowdownHighlights(id);}
 void ClearShowdownHighlight(){if(showdownHighlightPlayer<0)return;showdownHighlightPlayer=-1;ApplyShowdownHighlights(-1);}
  void DrawReferenceSeat(J p,int slot){double x=seatAnchors[slot,0],y=seatAnchors[slot,1];int id=p["id"].I;bool hero=id==0,avatarRight=slot>=4;bool empty=p["status"].S=="empty"||p["status"].S=="busted";bool folded=p["folded"].B;bool active=!Hand["actor"].Null&&Hand["actor"].I==id&&Hand["status"].S=="playing";bool winner=Hand["status"].S=="complete"&&ResultForPlayer(id)["won"].N>0;var best=id==showdownHighlightPlayer?BestCardsFor(id):null;double holeX=x+(hero?57:avatarRight?29:65),holeY=y-(hero?67:48)-(winner?11:0);if(!empty&&(!folded||hero)&&p["status"].S!="sittingOut"){UI.At(table,HoleFan(p,hero,best,winner,hero&&folded),holeX,holeY);var equity=AllInEquityBadge(id);if(equity!=null)UI.At(table,equity,holeX+(hero?105:89)*(winner?1.3:1)*TableCardScale,holeY+24);}
  var seat=new Canvas{Width=178,Height=85,ToolTip=p["name"].S+"\n"+SeatPosition(id,Hand)+" · "+Chips(p["stack"].N/Session["config"]["bb"].N)+" BB\n"+p["lastAction"].S};if(folded){seat.RenderTransform=new ScaleTransform(.8,.8);seat.RenderTransformOrigin=new Point(.5,.5);}var plate=new Border{Width=152,Height=64,CornerRadius=new CornerRadius(6),Background=UI.Brush("#252831"),BorderBrush=UI.Brush("#41434C"),BorderThickness=new Thickness(.7)};UI.At(seat,plate,avatarRight?0:26,0);double textX=avatarRight?6:78;string position=empty?"":SeatPosition(id,Hand);var role=TableText(position,10,UI.Brush("#D8B96C"),true);role.Width=94;role.Height=15;role.TextAlignment=TextAlignment.Center;role.TextTrimming=TextTrimming.CharacterEllipsis;UI.At(seat,role,textX,3);var name=TableText(empty?"空缺玩家":p["name"].S,13,UI.Brush("#D9DADF"));name.Width=94;name.Height=17;name.TextAlignment=TextAlignment.Center;name.TextTrimming=TextTrimming.CharacterEllipsis;name.LineHeight=14;UI.At(seat,name,textX,empty?12:18);UI.At(seat,new Line{X1=0,Y1=0,X2=89,Y2=0,Stroke=UI.Brush("#3D4149"),StrokeThickness=.7},textX+2,37);var money=UI.Stack(true);money.VerticalAlignment=VerticalAlignment.Center;var currency=CurrencyIcon();currency.VerticalAlignment=VerticalAlignment.Center;currency.Margin=new Thickness(0,0,4,0);money.Children.Add(currency);money.Children.Add(TableText(Chips(p["stack"].N),16,UI.Brush("#F0F0F2")));money.ToolTip="筹码 $"+Chips(p["stack"].N);UI.At(seat,money,textX+6,40);
  double avatarSize=winner?97.5:75,avatarX=avatarRight?100-(avatarSize-75):0,avatarY=-5-(avatarSize-75)/2;var face=Portrait(p,avatarSize);var placeholder=face as Grid;if(active&&placeholder!=null&&placeholder.Children.Count>1)placeholder.Children[1].Visibility=Visibility.Collapsed;if(folded||empty)face.Opacity=.43;if(winner)face.Effect=new DropShadowEffect{Color=Color.FromRgb(255,205,100),BlurRadius=15,ShadowDepth=0,Opacity=.92};UI.At(seat,face,avatarX,avatarY);if(active){var shade=new Ellipse{Width=73,Height=73,Fill=new SolidColorBrush(Color.FromArgb(65,0,0,0))};UI.At(seat,shade,avatarX+1,-4);UI.At(seat,new Ellipse{Width=75,Height=75,Stroke=UI.Brush("#345A8B"),StrokeThickness=2.2},avatarX,-5);countdownArc=new System.Windows.Shapes.Path{Stroke=UI.Brush("#65ADFF"),StrokeThickness=3.2,Width=75,Height=75};UI.At(seat,countdownArc,avatarX,-5);avatarCountdown=TableText("",29,Brushes.White,true);avatarCountdown.Width=75;avatarCountdown.Height=75;avatarCountdown.TextAlignment=TextAlignment.Center;avatarCountdown.VerticalAlignment=VerticalAlignment.Center;avatarCountdown.Padding=new Thickness(0,16,0,0);UI.At(seat,avatarCountdown,avatarX,-5);countdownSeat=id;}
  string rank=ShowdownRank(id);if(rank!=""){var rankText=TableText(rank,11,UI.Brush("#FFD77A"),true);rankText.TextAlignment=TextAlignment.Center;var rankTag=UI.Box(rankText,UI.Brush("#40331C"),5,new Thickness(5,1,5,1));rankTag.Width=70;rankTag.Height=22;UI.At(seat,rankTag,avatarRight?5:102,-23);}string managed=p["localManaged"].S;if(managed!=""){var managedText=TableText(managed,10,UI.Brush("#E7ECDD"),true);managedText.TextAlignment=TextAlignment.Center;var managedTag=UI.Box(managedText,UI.Brush("#79532D"),5,new Thickness(4,1,4,1));managedTag.Width=64;managedTag.Height=19;UI.At(seat,managedTag,avatarRight?104:3,68);}string action=ActionLabel(p);if(action!=""&&!hero){bool blind=action=="SB"||action=="BB",raise=action=="加注"||action=="下注";var label=TableText(action,12,blind?UI.Brush("#303239"):UI.Brush("#D5EADB"));label.TextAlignment=TextAlignment.Center;var tag=UI.Box(label,UI.Brush(blind?"#D5D8DF":raise?"#A6772E":action=="弃牌"?"#333741":"#207648"),0,new Thickness(0,2,0,2));tag.Width=76;tag.Height=21;UI.At(seat,tag,avatarRight?16:83,64);}if(!empty){seat.MouseEnter+=(s,e)=>SetShowdownHighlight(id);seat.MouseLeave+=(s,e)=>ClearShowdownHighlight();}if(!hero&&!empty){seat.Cursor=Cursors.Hand;seat.MouseLeftButtonUp+=(s,e)=>ShowPlayer(p);}UI.At(table,seat,x,y);
  if(hero&&!empty){seat.Cursor=Cursors.Hand;seat.MouseLeftButtonUp+=(s,e)=>ShowHeroStats();}
 }
 void DrawBet(J player,int slot){if(player["streetBet"].N<=0)return;double x=betAnchors[slot,0],y=betAnchors[slot,1];bool textFirst=slot>=4;var row=UI.Stack(true);var value=TableText(Chips(player["streetBet"].N),12,UI.Brush("#F5F0E5"),true);var badge=UI.Box(value,UI.Brush("#173D34"),6,new Thickness(4,1,4,1));badge.VerticalAlignment=VerticalAlignment.Center;var chip=ChipStack(3,22);chip.Margin=new Thickness(2,0,2,0);row.Children.Add(textFirst?(UIElement)badge:chip);row.Children.Add(textFirst?(UIElement)chip:badge);UI.At(table,row,x-24,y-11);}
 void DrawDealer(int slot){var g=new Grid{Width=32,Height=32};g.Children.Add(new Ellipse{Fill=UI.Brush("#F0F8F3"),Stroke=UI.Brush("#BDD4C8"),StrokeThickness=1.2});var t=TableText("D",18,UI.Brush("#252C2C"),true);t.TextAlignment=TextAlignment.Center;g.Children.Add(t);UI.At(table,g,dealerAnchors[slot,0]-16,dealerAnchors[slot,1]-16);}
 string HeroHandLabel(){var cards=Hero["hole"].Items.Concat(Hand["board"].Items).Select(c=>c.S).Where(c=>c.Length==2&&c!="??").ToArray();if(cards.Length<2)return "";var groups=cards.GroupBy(c=>c[0]).Select(g=>g.Count()).OrderByDescending(n=>n).ToArray();var flush=cards.GroupBy(c=>c[1]).FirstOrDefault(g=>g.Count()>=5);Func<IEnumerable<string>,bool> straight=values=>{var ranks=new HashSet<int>(values.Select(c=>"23456789TJQKA".IndexOf(c[0])+2));if(ranks.Contains(14))ranks.Add(1);return Enumerable.Range(1,10).Any(start=>Enumerable.Range(start,5).All(ranks.Contains));};if(flush!=null&&straight(flush))return "同花顺";if(groups[0]>=4)return "四条";if(groups[0]>=3&&groups.Skip(1).Any(n=>n>=2))return "葫芦";if(flush!=null)return "同花";if(straight(cards))return "顺子";if(groups[0]>=3)return "三条";if(groups.Count(n=>n>=2)>=2)return "两对";return groups[0]>=2?"一对":"高牌";}
 void Later(double seconds,Action action){Canvas owner=animationLayer;var timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(Math.Max(1,seconds*1000))};timer.Tick+=(s,e)=>{timer.Stop();if(owner==animationLayer)action();};timer.Start();}
 void MoveAnimated(FrameworkElement item,double fromX,double fromY,double toX,double toY,double delay=.0,double duration=.42,bool fadeOut=true){if(animationLayer==null)return;Canvas owner=animationLayer;var ease=new CubicEase{EasingMode=EasingMode.EaseInOut};UI.At(owner,item,fromX,fromY);item.Opacity=0;item.BeginAnimation(Canvas.LeftProperty,new DoubleAnimation(fromX,toX,TimeSpan.FromSeconds(duration)){BeginTime=TimeSpan.FromSeconds(delay),EasingFunction=ease});item.BeginAnimation(Canvas.TopProperty,new DoubleAnimation(fromY,toY,TimeSpan.FromSeconds(duration)){BeginTime=TimeSpan.FromSeconds(delay),EasingFunction=ease});item.BeginAnimation(UIElement.OpacityProperty,new DoubleAnimation(0,1,TimeSpan.FromSeconds(.075)){BeginTime=TimeSpan.FromSeconds(delay)});if(fadeOut){Later(delay+duration*.67,()=>item.BeginAnimation(UIElement.OpacityProperty,new DoubleAnimation(1,0,TimeSpan.FromSeconds(.22))));Later(delay+duration+.28,()=>owner.Children.Remove(item));}}
 Point HolePoint(J player,int slot,int card){bool hero=player["id"].I==0,avatarRight=slot>=4;return new Point(seatAnchors[slot,0]+(hero?57:avatarRight?29:65)+card*(hero?42:39)*TableCardScale,seatAnchors[slot,1]-(hero?67:48)+(card==0?0:TableCardScale));}
 Point BoardPoint(int index,int total){double spacing=55*TableCardScale;return new Point(750-total*spacing/2+index*spacing,309);}
 void AnimateInitialDeal(J[] players,int[] slots){var recipients=players.Select((player,index)=>new{player,index}).Where(x=>x.player["status"].S!="empty"&&x.player["status"].S!="busted"&&!x.player["folded"].B).ToArray();int sequence=0;for(int card=0;card<2;card++)foreach(var recipient in recipients){bool hero=recipient.player["id"].I==0;Point target=HolePoint(recipient.player,slots[recipient.index],card);var dealt=TableCard("",(hero?55:44)*TableCardScale);dealt.RenderTransform=new RotateTransform(card==0?-7:7);MoveAnimated(dealt,730+card*5,249+card*3,target.X,target.Y,.06+sequence++*.075,.29);}}
 void AnimateBoardCard(string value,int index,int total,double delay){Point target=BoardPoint(index,total);double width=49*TableCardScale;var face=TableCard(value,width);MoveAnimated(face,726+index*5,247,target.X,target.Y,delay,.42,false);Later(delay+.76,()=>animationLayer.Children.Remove(face));}
 void AnimateFold(int id,J[] players,int[] slots){int playerIndex=Array.FindIndex(players,p=>p["id"].I==id);if(playerIndex<0)return;J player=players[playerIndex];bool hero=id==0;for(int card=0;card<2;card++){Point start=HolePoint(player,slots[playerIndex],card);var thrown=TableCard("",(hero?55:44)*TableCardScale);thrown.RenderTransform=new RotateTransform(card==0?-16:12);MoveAnimated(thrown,start.X,start.Y,724+card*12,367+card*4,card*.06,.42);}}
 void AnimateBetChips(int id,J[] players,int[] slots){int playerIndex=Array.FindIndex(players,p=>p["id"].I==id);if(playerIndex<0||animationLayer==null)return;Point target=new Point(betAnchors[slots[playerIndex],0]-8,betAnchors[slots[playerIndex],1]-10);for(int stage=1;stage<=3;stage++){int current=stage;var chip=ChipStack(current,16+current*2);var scale=new ScaleTransform(.68,.68);chip.RenderTransform=scale;chip.RenderTransformOrigin=new Point(.5,.5);double delay=(stage-1)*.095;UI.At(animationLayer,chip,target.X+(stage-1)*2,target.Y-(stage-1));chip.Opacity=0;chip.BeginAnimation(UIElement.OpacityProperty,new DoubleAnimation(0,1,TimeSpan.FromSeconds(.11)){BeginTime=TimeSpan.FromSeconds(delay)});scale.BeginAnimation(ScaleTransform.ScaleXProperty,new DoubleAnimation(.68,.78,TimeSpan.FromSeconds(.16)){BeginTime=TimeSpan.FromSeconds(delay),EasingFunction=new CubicEase{EasingMode=EasingMode.EaseOut}});scale.BeginAnimation(ScaleTransform.ScaleYProperty,new DoubleAnimation(.68,.78,TimeSpan.FromSeconds(.16)){BeginTime=TimeSpan.FromSeconds(delay),EasingFunction=new CubicEase{EasingMode=EasingMode.EaseOut}});if(stage==3)Later(delay+.72,()=>animationLayer.Children.Remove(chip));}}
 void AnimatePayout(J[] players,int[] slots){var winners=Hand["results"].Items.Where(r=>r["won"].N>0).ToArray();if(!winners.Any())return;PlayLargeChipSound();foreach(J winner in winners){int index=Array.FindIndex(players,p=>p["id"].I==winner["playerId"].I);if(index<0)continue;int pieces=Math.Max(7,Math.Min(16,(int)Math.Ceiling(winner["won"].N/Math.Max(1,Hand["pot"].N)*16)));double endX=seatAnchors[slots[index],0]+68,endY=seatAnchors[slots[index],1]+22;for(int piece=0;piece<pieces;piece++){var chip=ChipStack();chip.RenderTransform=new ScaleTransform(.72,.72);MoveAnimated(chip,739+(piece%5)*5,366+(piece%4)*4,endX+(piece%3-1)*9,endY+(piece%4-2)*4,piece*.045,.5);}}}
 void PlayTableAnimations(J[] players,int[] slots,bool newHand){if(animationLayer==null)return;int boardCount=Hand["board"].Items.Count();if(newHand){renderedEventSeq=Hand["events"].Items.Select(e=>e["seq"].I).DefaultIfEmpty(-1).Max();renderedBoardCount=boardCount;AnimateInitialDeal(players,slots);return;}var events=Hand["events"].Items.OrderBy(e=>e["seq"].I).ToArray();foreach(J e in events.Where(e=>e["seq"].I>renderedEventSeq&&e["type"].S=="action")){if(e["action"].S=="fold")AnimateFold(e["playerId"].I,players,slots);else if(e["amount"].N>0)AnimateBetChips(e["playerId"].I,players,slots);}renderedEventSeq=Math.Max(renderedEventSeq,events.Select(e=>e["seq"].I).DefaultIfEmpty(-1).Max());if(boardCount>renderedBoardCount){for(int i=renderedBoardCount;i<boardCount;i++)AnimateBoardCard(Hand["board"][i].S,i,boardCount,(i-renderedBoardCount)*.13);renderedBoardCount=boardCount;}if(Hand["status"].S=="complete"&&payoutAnimationKey!=seenHand){payoutAnimationKey=seenHand;AnimatePayout(players,slots);}}
 void SyncBotVisualCountdown(){string key="";if(!Session.Null&&!Hand["actor"].Null&&Hand["actor"].I!=0&&Hand["status"].S=="playing")key=Session["id"].S+"/"+Hand["number"].S+"/"+Hand["eventCount"].S+"/"+Hand["actor"].S;if(key!=botVisualCountdownKey){botVisualCountdownKey=key;botVisualCountdownStartedAt=key==""?0:new DateTimeOffset(DateTime.UtcNow).ToUnixTimeMilliseconds();}}
 void RenderTable(){table=new Canvas{Width=TableWidth,Height=TableHeight,ClipToBounds=true,Background=SceneForLevel()};showdownCardViews.Clear();body.Children.Add(new Viewbox{Stretch=Stretch.Fill,Child=table});var players=Session["players"].Items.ToArray();J h=Hand;string key=Session["id"].S+"/"+h["number"].S;bool newHand=seenHand!=key;if(newHand){seenHand=key;fastFold=false;reviewHold=false;settleAt=DateTime.MaxValue;raiseTo=0;showdownHighlightPlayer=-1;payoutAnimationKey="";}if(h["street"].S!="preflop")fastFold=false;avatarCountdown=null;countdownArc=null;countdownSeat=-1;SyncBotVisualCountdown();betSlider=null;betInput=null;raiseButton=null;compactReviewButton=null;
  var menu=TableButton("",ShowMenu,48,46);menu.Background=new SolidColorBrush(Color.FromArgb(70,0,0,0));menu.BorderThickness=new Thickness(0);var hamburger=new Canvas{Width=23,Height=24};for(int i=0;i<3;i++)UI.At(hamburger,new Border{Width=21,Height=2.5,Background=UI.Brush("#DEE3DC"),CornerRadius=new CornerRadius(1)},0,3+i*8);menu.Content=hamburger;menu.ToolTip="牌桌菜单：暂停、补码、保存、设置、返回大厅";UI.At(table,menu,20,23);compactReviewButton=CompactReviewButton();UI.At(table,compactReviewButton,76,23);
  var info=UI.Stack();var heading=TableText("BLINDS",12,UI.Brush("#A9AAB2"));heading.TextAlignment=TextAlignment.Center;info.Children.Add(heading);string blinds=Chips(Session["config"]["sb"].N)+"/"+Chips(Session["config"]["bb"].N)+(Session["config"]["straddleEnabled"].B?"/"+Chips(Session["config"]["straddle"].N):"");var limits=TableText(blinds,15);limits.TextAlignment=TextAlignment.Center;info.Children.Add(limits);var blindBox=UI.Box(info,UI.Brush("#20222F"),5,new Thickness(7,6,7,6));blindBox.Width=178;blindBox.Height=50;blindBox.ToolTip="当前盲注";UI.At(table,blindBox,1309,11);
   var potrow=UI.Stack(true);potrow.Children.Add(TableText("POT: ",16,UI.Brush("#BDE5D8")));var potIcon=CurrencyIcon(13);potIcon.Margin=new Thickness(2,0,5,0);potIcon.VerticalAlignment=VerticalAlignment.Center;potrow.Children.Add(potIcon);potrow.Children.Add(TableText(Chips(h["pot"].N),16,UI.Brush("#D3EFE2")));var pot=UI.Box(potrow,UI.Brush("#12634F"),3,new Thickness(8,2,8,3));pot.ToolTip=Chips(h["pot"].N/Session["config"]["bb"].N)+" BB";pot.Measure(new Size(500,100));UI.At(table,pot,750-pot.DesiredSize.Width/2,263);if(h["importantHand"]["potBB"].N>=100){var importantText=TableText("★ 重要牌局 · "+h["importantHand"]["potBB"].S+" BB",12,UI.Brush("#FFE09A"),true);var importantTag=UI.Box(importantText,UI.Brush("#493719"),7,new Thickness(8,3,8,3));importantTag.ToolTip="本手底池达到 100BB，已记录为重要牌局";importantTag.Measure(new Size(300,50));UI.At(table,importantTag,750-importantTag.DesiredSize.Width/2,289);}
  var boardHighlights=BestCardsFor(showdownHighlightPlayer);if(h["board"].Items.Any()){var board=UI.Stack(true);foreach(var c in h["board"].Items){var card=TableCard(c.S,49*TableCardScale,boardHighlights.Contains(c.S));RegisterShowdownCard(c.S,card);card.Margin=new Thickness(3*TableCardScale,0,3*TableCardScale,0);board.Children.Add(card);}board.Measure(new Size(500,120));UI.At(table,board,750-board.DesiredSize.Width/2,309);}
  int[] slots=SeatSlots(players.Length);for(int i=0;i<players.Length;i++){DrawReferenceSeat(players[i],slots[i]);DrawBet(players[i],slots[i]);}for(int i=0;i<players.Length;i++)if(players[i]["id"].I==h["button"].I)DrawDealer(slots[i]);
  if(!Hero["folded"].B){var strength=TableText(HeroHandLabel(),14,UI.Brush("#86C6AB"));strength.Width=130;strength.TextAlignment=TextAlignment.Center;UI.At(table,strength,699,465);}
  var hands=TableButton("第 "+h["number"].I+" 手牌",async()=>{reviewHold=h["status"].S=="complete";await ShowCompact();},82,26);hands.FontSize=10;hands.Background=Brushes.Transparent;hands.BorderThickness=new Thickness(0);hands.Foreground=UI.Brush("#C7C7C9");hands.ToolTip="本局精简复盘 · 浏览已完成手牌";UI.At(table,hands,19,700);var room=UI.Stack(true);room.VerticalAlignment=VerticalAlignment.Center;room.Children.Add(TableText("房间剩余",11,UI.Brush("#9CB3AB")));clockText=TableText("--:--:--",14,UI.Brush("#E5D29A"),true);clockText.Margin=new Thickness(8,0,0,0);room.Children.Add(clockText);var roomBox=UI.Box(room,UI.Brush("#10211D"),5,new Thickness(9,4,9,4));UI.At(table,roomBox,19,730);actionClock=TableText("",13,UI.Brush("#D3D6DD"));actionClock.Width=360;actionClock.Visibility=h["status"].S=="complete"||h["allInShowdown"].B?Visibility.Visible:Visibility.Collapsed;UI.At(table,actionClock,970,760);
  if(h["status"].S=="complete"){if(settleAt==DateTime.MaxValue)settleAt=DateTime.UtcNow.AddSeconds(ResultRevealSeconds);var row=UI.Stack(true);row.Children.Add(TableButton("精简复盘",async()=>{reviewHold=true;await ShowCompact();},130,50));if(h["canShow"].B)row.Children.Add(TableButton("亮出底牌",async()=>await Run("show",Turn()),120,50));if(Session["config"]["straddleEnabled"].B)row.Children.Add(TableButton(straddleNext?"✓ 下手 Straddle":"下手 Straddle",()=>{straddleNext=!straddleNext;Render();},140,50));row.Children.Add(TableButton("立即下一手",async()=>await NextHand(),140,50,true));UI.At(table,row,963,699);}else if(!h["legal"].Null)RenderActions();else if(!Hero["folded"].B&&h["street"].S=="preflop"&&h["pending"].Items.Any(x=>x.I==0))UI.At(table,TableButton("快速弃牌  [F]",ToggleFastFold,165,63),1326,695);
  animationLayer=new Canvas{Width=TableWidth,Height=TableHeight,IsHitTestVisible=false,ClipToBounds=true};UI.At(table,animationLayer,0,0);PlayTableAnimations(players,slots,newHand);
 }
 void SetBet(double amount){if(betSlider==null||syncingBet)return;syncingBet=true;raiseTo=Math.Round(Math.Max(betSlider.Minimum,Math.Min(betSlider.Maximum,amount)));betSlider.Value=raiseTo;betInput.Text=Chips(raiseTo);SetActionCaption(raiseButton,!Hand["legal"]["canRaise"].B&&Hand["legal"]["canAllIn"].B?"全下":"加注到",Chips(raiseTo));syncingBet=false;}
 void SetActionCaption(Button button,string label,string amount){if(button==null)return;var text=TableText("",amount==""?24:17,Brushes.White,true);text.TextAlignment=TextAlignment.Center;text.LineHeight=24;text.Inlines.Add(new Run(label));if(amount!=""){text.Inlines.Add(new LineBreak());text.Inlines.Add(new Run(amount){FontSize=23});}button.Content=text;}

 void RenderActions(){J legal=Hand["legal"];double minimum=Math.Min(legal["minRaiseTo"].N,legal["maxRaiseTo"].N),maximum=legal["maxRaiseTo"].N;raiseTo=Math.Max(minimum,Math.Min(maximum,raiseTo));bool canRaise=legal["canRaise"].B&&!paused;bool canAllIn=legal["canAllIn"].B&&!paused;var presets=new Grid{Width=338,Height=32};for(int i=0;i<4;i++)presets.ColumnDefinitions.Add(new ColumnDefinition());bool preflop=Hand["street"].S=="preflop";for(int i=0;i<4;i++){int index=i;string label=i==3?"全下":preflop?(i+2)+"x":new[]{"33%","50%","100%"}[i];var preset=TableButton(label,()=>{double amount=index==3?maximum:preflop?Hand["currentBet"].N*(index+2):Hand["currentBet"].N+(Hand["pot"].N+legal["toCall"].N)*new[]{.33,.5,1}[index];SetBet(amount);},84.5,32);preset.FontSize=13;preset.FontWeight=FontWeights.Normal;string corner=i==0?"6,0,0,6":i==3?"0,6,6,0":"0";preset.Template=(ControlTemplate)XamlReader.Parse("<ControlTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='Button'><Border x:Name='frame' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='1' CornerRadius='"+corner+"'><ContentPresenter HorizontalAlignment='Center' VerticalAlignment='Center'/></Border><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='frame' Property='Opacity' Value='.8'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter TargetName='frame' Property='Opacity' Value='.35'/></Trigger></ControlTemplate.Triggers></ControlTemplate>");preset.IsEnabled=i==3?canAllIn:canRaise;Grid.SetColumn(preset,i);presets.Children.Add(preset);}UI.At(table,presets,1150,604);
  var track=new Border{Width=220,Height=33,Background=UI.Brush("#242936"),CornerRadius=new CornerRadius(8),BorderBrush=UI.Brush("#303743"),BorderThickness=new Thickness(1)};UI.At(table,track,1145,646);var minus=TableButton("−",()=>SetBet(raiseTo-Session["config"]["bb"].N),30,31);minus.Background=Brushes.Transparent;minus.BorderThickness=new Thickness(0);minus.IsEnabled=canRaise;UI.At(table,minus,1146,647);betSlider=new Slider{Minimum=minimum,Maximum=Math.Max(minimum,maximum),Value=raiseTo,Width=160,Height=31,TickFrequency=1,IsSnapToTickEnabled=true,IsEnabled=canRaise,Orientation=Orientation.Horizontal,Focusable=true};betSlider.Template=(ControlTemplate)XamlReader.Parse("<ControlTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml' TargetType='Slider'><Grid Background='Transparent'><Border Height='4' Background='#777A85' VerticalAlignment='Center' Margin='8,0'/><Track x:Name='PART_Track' Minimum='{TemplateBinding Minimum}' Maximum='{TemplateBinding Maximum}' Value='{TemplateBinding Value}' Orientation='Horizontal'><Track.DecreaseRepeatButton><RepeatButton Command='Slider.DecreaseLarge' Opacity='0'/></Track.DecreaseRepeatButton><Track.Thumb><Thumb Width='18' Height='18'><Thumb.Template><ControlTemplate TargetType='Thumb'><Ellipse Fill='#242731' Stroke='#8A8B93' StrokeThickness='1.4'/></ControlTemplate></Thumb.Template></Thumb></Track.Thumb><Track.IncreaseRepeatButton><RepeatButton Command='Slider.IncreaseLarge' Opacity='0'/></Track.IncreaseRepeatButton></Track></Grid></ControlTemplate>");UI.At(table,betSlider,1177,647);var plus=TableButton("+",()=>SetBet(raiseTo+Session["config"]["bb"].N),28,31);plus.Background=Brushes.Transparent;plus.BorderThickness=new Thickness(0);plus.IsEnabled=canRaise;UI.At(table,plus,1335,647);
  betInput=new TextBox{Text=Chips(raiseTo),Width=106,Height=32,Background=UI.Brush("#0E0C0A"),Foreground=Brushes.White,BorderThickness=new Thickness(0),FontFamily=new FontFamily("Segoe UI"),FontSize=21,TextAlignment=TextAlignment.Center,VerticalContentAlignment=VerticalAlignment.Center,IsEnabled=canRaise};UI.At(table,betInput,1382,647);betSlider.ValueChanged+=(s,e)=>SetBet(e.NewValue);betInput.LostFocus+=(s,e)=>CommitBetInput();betInput.KeyDown+=(s,e)=>{if(e.Key==Key.Enter){CommitBetInput();e.Handled=true;}};
  var fold=TableButton("",async()=>await Act("fold"),165,64,true);SetActionCaption(fold,"弃牌","");fold.IsEnabled=!paused;UI.At(table,fold,971,695);var call=TableButton("",async()=>await Act(legal["canCheck"].B?"check":"call"),165,64,true);SetActionCaption(call,legal["canCheck"].B?"过牌":"跟注",legal["canCheck"].B?"":Chips(legal["toCall"].N));call.IsEnabled=!paused;UI.At(table,call,1149,695);raiseButton=TableButton("",async()=>{if(CommitBetInput())await Act(raiseTo>=maximum&&legal["canAllIn"].B?"allin":"raise",raiseTo);},165,64,true);raiseButton.IsEnabled=canRaise||canAllIn;SetActionCaption(raiseButton,!Hand["legal"]["canRaise"].B&&Hand["legal"]["canAllIn"].B?"全下":"加注到",Chips(raiseTo));UI.At(table,raiseButton,1327,695);
  var extend=TableButton("◴ +20s",async()=>await Run("extend",Turn()),110,29);extend.FontSize=12;extend.Foreground=UI.Brush("#75ACDF");extend.Background=new SolidColorBrush(Color.FromArgb(190,37,40,48));extend.BorderThickness=new Thickness(0);extend.IsEnabled=Hand["actionExtensions"].I==0&&!paused;extend.ToolTip="本手一次，增加 20 秒思考时间";extendButton=extend;UI.At(table,extend,535,578);
 }
 bool CommitBetInput(){double amount;if(betInput==null||!double.TryParse(betInput.Text,System.Globalization.NumberStyles.Number,System.Globalization.CultureInfo.InvariantCulture,out amount)||double.IsNaN(amount)||double.IsInfinity(amount)){Notice("请输入有效的加注金额。");if(betInput!=null)betInput.Text=Chips(raiseTo);return false;}SetBet(amount);return true;}
 void UpdateAvatarClock(double? sampleTime=null){if(avatarCountdown==null||countdownArc==null)return;double now=sampleTime??(paused?new DateTimeOffset(pauseAt).ToUnixTimeMilliseconds():DateTimeOffset.UtcNow.ToUnixTimeMilliseconds());bool bot=countdownSeat!=0;double reportedBotStart=Hand["botTiming"]["startedAt"].N,start=bot?(reportedBotStart>0?reportedBotStart:botVisualCountdownStartedAt):Hand["actionStartedAt"].N,botWindow=state["ai"]["mode"].S=="external"&&state["ai"]["actionWindowMs"].N>0?state["ai"]["actionWindowMs"].N:20000,deadline=bot&&start>0?start+botWindow:bot?0:Hand["actionDeadlineAt"].N;double seconds=Math.Max(0,Math.Ceiling((deadline-now)/1000));avatarCountdown.Text=paused?"Ⅱ":deadline>0?seconds.ToString():"···";double fraction=deadline<=start?1:Math.Max(.002,Math.Min(.999,(deadline-now)/(deadline-start)));double angle=2*Math.PI*fraction;var path=new PathFigure{StartPoint=new Point(37.5,1.8)};path.Segments.Add(new ArcSegment(new Point(37.5+35.7*Math.Sin(angle),37.5-35.7*Math.Cos(angle)),new Size(35.7,35.7),0,fraction>.5,SweepDirection.Clockwise,true));countdownArc.Data=new PathGeometry(new[]{path});}
}
}
